package ru.runa.wfe.presentation;

public enum ClassPresentationType {
    NONE, SYSTEM_LOG, EXECUTOR, ACTOR, GROUP, RELATION, RELATIONPAIR, DEFINITION, DEFINITION_HISTORY, PROCESS, TASK, TASK_SIMPLE, REPORTS;
}
