import Vue from 'vue';
import Links from '../components/Links.vue';
import MaterialAlert from '../components/MaterialAlert.vue';
import MaterialCard from '../components/MaterialCard.vue';
import MaterialChartCard from '../components/MaterialChartCard.vue';
import MaterialSnackbar from '../components/MaterialSnackbar.vue';
import MaterialStatCard from '../components/MaterialStatCard.vue';
import ViewIntro from '../components/ViewIntro.vue';
import AppBarItem from '../components/app/BarItem.vue';
import AppBtn from '../components/app/Btn.vue';
import AppCard from '../components/app/Card.vue';
import AppTabs from '../components/app/Tabs.vue';

Vue.component('Links', Links);
Vue.component('MaterialAlert', MaterialAlert);
Vue.component('MaterialCard', MaterialCard);
Vue.component('MaterialChartCard', MaterialChartCard);
Vue.component('MaterialSnackbar', MaterialSnackbar);
Vue.component('MaterialStatCard', MaterialStatCard);
Vue.component('ViewIntro', ViewIntro);
Vue.component('AppBarItem', AppBarItem);
Vue.component('AppBtn', AppBtn);
Vue.component('AppCard', AppCard);
Vue.component('AppTabs', AppTabs);
