//
// ATTENTION!!! This file is auto-generated by wfe-codegen-dbaware subproject. See README.txt there.
//
package ru.runa.wfe.commons.dbpatch;

import com.google.common.collect.ImmutableList;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.Timestamp;
import java.util.List;

public class DbPatch0 extends DbPatch {

    @Override
    protected List<String> getDDLQueriesBefore() {
        return ImmutableList.of(
                getDDLCreateTable("actor_password", ImmutableList.of(
                        new BigintColumnDef("actor_id", false).setPrimaryKey(),
                        new BlobColumnDef("password", false)
                )),
                getDDLCreateTable("admin_script", ImmutableList.of(
                        new BigintColumnDef("id", false).setPrimaryKey(),
                        new VarcharColumnDef("name", 1024, true),
                        new BlobColumnDef("content", true)
                )),
                getDDLCreateTable("archived_log", ImmutableList.of(
                        new CharColumnDef("discriminator", 1, false),
                        new BigintColumnDef("id", false).setPrimaryKey(),
                        new VarcharColumnDef("severity", 1024, false),
                        new BigintColumnDef("token_id", true),
                        new VarcharColumnDef("node_id", 1024, true),
                        new TimestampColumnDef("create_date", false),
                        new BlobColumnDef("bytes", true),
                        new VarcharColumnDef("content", 4000, true),
                        new BigintColumnDef("process_id", false)
                )),
                getDDLCreateTable("archived_process", ImmutableList.of(
                        new BigintColumnDef("id", false).setPrimaryKey(),
                        new BigintColumnDef("parent_id", true),
                        new BigintColumnDef("version", true),
                        new VarcharColumnDef("tree_path", 1024, true),
                        new TimestampColumnDef("start_date", true),
                        new TimestampColumnDef("end_date", true),
                        new BigintColumnDef("root_token_id", false),
                        new BigintColumnDef("definition_version_id", false)
                )),
                getDDLCreateTable("archived_subprocess", ImmutableList.of(
                        new BigintColumnDef("id", false).setPrimaryKey(),
                        new VarcharColumnDef("parent_node_id", 1024, true),
                        new IntColumnDef("subprocess_index", true),
                        new TimestampColumnDef("create_date", false),
                        new BigintColumnDef("process_id", false),
                        new BigintColumnDef("parent_token_id", true),
                        new BigintColumnDef("root_process_id", false),
                        new BigintColumnDef("parent_process_id", false)
                )),
                getDDLCreateTable("archived_swimlane", ImmutableList.of(
                        new BigintColumnDef("id", false).setPrimaryKey(),
                        new BigintColumnDef("version", true),
                        new VarcharColumnDef("name", 1024, true),
                        new TimestampColumnDef("create_date", false),
                        new BigintColumnDef("process_id", true),
                        new BigintColumnDef("executor_id", true)
                )),
                getDDLCreateTable("archived_token", ImmutableList.of(
                        new BigintColumnDef("id", false).setPrimaryKey(),
                        new BigintColumnDef("version", true),
                        new VarcharColumnDef("name", 1024, true),
                        new VarcharColumnDef("node_type", 1024, true),
                        new VarcharColumnDef("node_id", 1024, true),
                        new VarcharColumnDef("transition_id", 1024, true),
                        new TimestampColumnDef("start_date", true),
                        new TimestampColumnDef("end_date", true),
                        new BooleanColumnDef("reactivate_parent", true),
                        new TimestampColumnDef("error_date", true),
                        new VarcharColumnDef("error_message", 1024, true),
                        new VarcharColumnDef("message_selector", 1024, true),
                        new BigintColumnDef("parent_id", true),
                        new BigintColumnDef("process_id", true)
                )),
                getDDLCreateTable("archived_variable", ImmutableList.of(
                        new CharColumnDef("discriminator", 1, false),
                        new BigintColumnDef("id", false).setPrimaryKey(),
                        new VarcharColumnDef("stringvalue", 1024, true),
                        new TimestampColumnDef("create_date", false),
                        new CharColumnDef("converter", 1, true),
                        new BigintColumnDef("version", true),
                        new VarcharColumnDef("name", 1024, true),
                        new BlobColumnDef("bytes", true),
                        new BigintColumnDef("longvalue", true),
                        new DoubleColumnDef("doublevalue", true),
                        new TimestampColumnDef("datevalue", true),
                        new BigintColumnDef("process_id", false)
                )),
                getDDLCreateTable("batch_presentation", ImmutableList.of(
                        new BigintColumnDef("id", false).setPrimaryKey(),
                        new VarcharColumnDef("category", 1024, false),
                        new BlobColumnDef("fields", true),
                        new IntColumnDef("range_size", true),
                        new TimestampColumnDef("create_date", false),
                        new BigintColumnDef("version", true),
                        new BooleanColumnDef("shared", false),
                        new BooleanColumnDef("is_active", true),
                        new VarcharColumnDef("name", 1024, false),
                        new VarcharColumnDef("class_type", 1024, true),
                        new BigintColumnDef("profile_id", true)
                )),
                getDDLCreateTable("bot", ImmutableList.of(
                        new BigintColumnDef("id", false).setPrimaryKey(),
                        new BooleanColumnDef("is_transactional", true),
                        new VarcharColumnDef("password", 1024, true),
                        new BooleanColumnDef("is_sequential", true),
                        new BigintColumnDef("transactional_timeout", true),
                        new TimestampColumnDef("bound_due_date", true),
                        new BigintColumnDef("bound_process_id", true),
                        new VarcharColumnDef("bound_subprocess_id", 255, true),
                        new VarcharColumnDef("username", 1024, true),
                        new TimestampColumnDef("create_date", false),
                        new BigintColumnDef("version", true),
                        new BigintColumnDef("bot_station_id", false)
                )),
                getDDLCreateTable("bot_station", ImmutableList.of(
                        new BigintColumnDef("id", false).setPrimaryKey(),
                        new BigintColumnDef("version", true),
                        new VarcharColumnDef("name", 1024, false),
                        new VarcharColumnDef("address", 1024, true),
                        new TimestampColumnDef("create_date", false)
                )),
                getDDLCreateTable("bot_task", ImmutableList.of(
                        new BigintColumnDef("id", false).setPrimaryKey(),
                        new BlobColumnDef("embedded_file", true),
                        new VarcharColumnDef("embedded_file_name", 1024, true),
                        new BooleanColumnDef("is_sequential", true),
                        new VarcharColumnDef("task_handler", 1024, true),
                        new TimestampColumnDef("create_date", false),
                        new BigintColumnDef("version", true),
                        new BlobColumnDef("configuration", true),
                        new VarcharColumnDef("name", 1024, true),
                        new BigintColumnDef("bot_id", false)
                )),
                getDDLCreateTable("bpm_agglog_assignments", ImmutableList.of(
                        new CharColumnDef("discriminator", 1, false),
                        new BigintColumnDef("id", false).setPrimaryKey(),
                        new TimestampColumnDef("assignment_date", false),
                        new VarcharColumnDef("new_executor_name", 1024, true),
                        new VarcharColumnDef("old_executor_name", 1024, true),
                        new BigintColumnDef("assignment_object_id", true),
                        new IntColumnDef("idx", true)
                )),
                getDDLCreateTable("bpm_agglog_process", ImmutableList.of(
                        new BigintColumnDef("id", false).setPrimaryKey(),
                        new VarcharColumnDef("cancel_actor_name", 1024, true),
                        new BigintColumnDef("process_id", false),
                        new BigintColumnDef("parent_process_id", true),
                        new VarcharColumnDef("start_actor_name", 1024, true),
                        new TimestampColumnDef("end_date", true),
                        new IntColumnDef("end_reason", false),
                        new TimestampColumnDef("create_date", false)
                )),
                getDDLCreateTable("bpm_agglog_tasks", ImmutableList.of(
                        new BigintColumnDef("id", false).setPrimaryKey(),
                        new VarcharColumnDef("task_name", 1024, false),
                        new BigintColumnDef("task_id", false),
                        new BigintColumnDef("token_id", false),
                        new VarcharColumnDef("swimlane_name", 1024, true),
                        new TimestampColumnDef("deadline_date", true),
                        new TimestampColumnDef("end_date", true),
                        new VarcharColumnDef("initial_actor_name", 1024, true),
                        new VarcharColumnDef("complete_actor_name", 1024, true),
                        new IntColumnDef("end_reason", false),
                        new VarcharColumnDef("node_id", 1024, false),
                        new IntColumnDef("task_index", true),
                        new TimestampColumnDef("create_date", false),
                        new BigintColumnDef("process_id", false)
                )),
                getDDLCreateTable("bpm_job", ImmutableList.of(
                        new CharColumnDef("discriminator", 1, false),
                        new BigintColumnDef("id", false).setPrimaryKey(),
                        new TimestampColumnDef("due_date", true),
                        new VarcharColumnDef("due_date_expression", 255, true),
                        new TimestampColumnDef("create_date", false),
                        new BigintColumnDef("version", true),
                        new VarcharColumnDef("name", 1024, true),
                        new VarcharColumnDef("repeat_duration", 1024, true),
                        new VarcharColumnDef("transition_name", 1024, true),
                        new BigintColumnDef("process_id", false),
                        new BigintColumnDef("token_id", true)
                )),
                getDDLCreateTable("bpm_log", ImmutableList.of(
                        new CharColumnDef("discriminator", 1, false),
                        new BigintColumnDef("id", false).setPrimaryKey(),
                        new VarcharColumnDef("severity", 1024, false),
                        new BigintColumnDef("token_id", true),
                        new VarcharColumnDef("node_id", 1024, true),
                        new TimestampColumnDef("create_date", false),
                        new BlobColumnDef("bytes", true),
                        new VarcharColumnDef("content", 4000, true),
                        new BigintColumnDef("process_id", false)
                )),
                getDDLCreateTable("bpm_process", ImmutableList.of(
                        new BigintColumnDef("id", false).setPrimaryKey(),
                        new BigintColumnDef("parent_id", true),
                        new BigintColumnDef("version", true),
                        new VarcharColumnDef("tree_path", 1024, true),
                        new TimestampColumnDef("start_date", true),
                        new TimestampColumnDef("end_date", true),
                        new VarcharColumnDef("execution_status", 255, false),
                        new BigintColumnDef("definition_version_id", false),
                        new BigintColumnDef("root_token_id", false)
                )),
                getDDLCreateTable("bpm_process_definition", ImmutableList.of(
                        new BigintColumnDef("id", false).setPrimaryKey(),
                        new IntColumnDef("seconds_before_archiving", true),
                        new VarcharColumnDef("category", 1024, false),
                        new VarcharColumnDef("description", 1024, true),
                        new VarcharColumnDef("name", 1024, false),
                        new VarcharColumnDef("language", 4, false),
                        new BigintColumnDef("latest_version_id", true)
                )),
                getDDLCreateTable("bpm_process_definition_ver", ImmutableList.of(
                        new BigintColumnDef("id", false).setPrimaryKey(),
                        new BigintColumnDef("subversion", false),
                        new TimestampColumnDef("subprocess_binding_date", true),
                        new TimestampColumnDef("update_date", true),
                        new TimestampColumnDef("create_date", false),
                        new BigintColumnDef("version", false),
                        new BlobColumnDef("bytes", true),
                        new BigintColumnDef("create_user_id", true),
                        new BigintColumnDef("update_user_id", true),
                        new BigintColumnDef("definition_id", false)
                )),
                getDDLCreateTable("bpm_setting", ImmutableList.of(
                        new BigintColumnDef("id", false).setPrimaryKey(),
                        new VarcharColumnDef("name", 1024, false),
                        new VarcharColumnDef("value", 1024, true),
                        new VarcharColumnDef("file_name", 1024, false)
                )),
                getDDLCreateTable("bpm_subprocess", ImmutableList.of(
                        new BigintColumnDef("id", false).setPrimaryKey(),
                        new VarcharColumnDef("parent_node_id", 1024, true),
                        new IntColumnDef("subprocess_index", true),
                        new TimestampColumnDef("create_date", false),
                        new BigintColumnDef("parent_token_id", true),
                        new BigintColumnDef("process_id", false),
                        new BigintColumnDef("parent_process_id", false),
                        new BigintColumnDef("root_process_id", false)
                )),
                getDDLCreateTable("bpm_swimlane", ImmutableList.of(
                        new BigintColumnDef("id", false).setPrimaryKey(),
                        new BigintColumnDef("version", true),
                        new VarcharColumnDef("name", 1024, true),
                        new TimestampColumnDef("create_date", false),
                        new BigintColumnDef("executor_id", true),
                        new BigintColumnDef("process_id", true)
                )),
                getDDLCreateTable("bpm_task", ImmutableList.of(
                        new BigintColumnDef("id", false).setPrimaryKey(),
                        new TimestampColumnDef("deadline_date", true),
                        new TimestampColumnDef("assign_date", true),
                        new VarcharColumnDef("deadline_date_expression", 255, true),
                        new VarcharColumnDef("node_id", 1024, true),
                        new TimestampColumnDef("create_date", false),
                        new BigintColumnDef("version", true),
                        new IntColumnDef("task_index", true),
                        new VarcharColumnDef("description", 1024, true),
                        new VarcharColumnDef("name", 1024, true),
                        new BigintColumnDef("process_id", true),
                        new BigintColumnDef("executor_id", true),
                        new BigintColumnDef("token_id", true),
                        new BigintColumnDef("swimlane_id", true)
                )),
                getDDLCreateTable("bpm_task_opened", ImmutableList.of(
                        new BigintColumnDef("task_id", false),
                        new BigintColumnDef("executor_id", true)
                )),
                getDDLCreateTable("bpm_token", ImmutableList.of(
                        new BigintColumnDef("id", false).setPrimaryKey(),
                        new BigintColumnDef("version", true),
                        new VarcharColumnDef("name", 1024, true),
                        new VarcharColumnDef("node_type", 1024, true),
                        new VarcharColumnDef("node_id", 1024, true),
                        new VarcharColumnDef("transition_id", 1024, true),
                        new TimestampColumnDef("start_date", true),
                        new TimestampColumnDef("end_date", true),
                        new BooleanColumnDef("reactivate_parent", true),
                        new TimestampColumnDef("error_date", true),
                        new VarcharColumnDef("error_message", 1024, true),
                        new VarcharColumnDef("execution_status", 255, false),
                        new VarcharColumnDef("message_selector", 1024, true),
                        new BigintColumnDef("process_id", true),
                        new BigintColumnDef("parent_id", true)
                )),
                getDDLCreateTable("bpm_variable", ImmutableList.of(
                        new CharColumnDef("discriminator", 1, false),
                        new BigintColumnDef("id", false).setPrimaryKey(),
                        new VarcharColumnDef("stringvalue", 1024, true),
                        new TimestampColumnDef("create_date", false),
                        new CharColumnDef("converter", 1, true),
                        new BigintColumnDef("version", true),
                        new VarcharColumnDef("name", 1024, true),
                        new TimestampColumnDef("datevalue", true),
                        new BigintColumnDef("longvalue", true),
                        new BlobColumnDef("bytes", true),
                        new DoubleColumnDef("doublevalue", true),
                        new BigintColumnDef("process_id", false)
                )),
                getDDLCreateTable("db_migration", ImmutableList.of(
                        new VarcharColumnDef("name", 255, false).setPrimaryKey(),
                        new TimestampColumnDef("when_started", false),
                        new TimestampColumnDef("when_finished", true)
                )),
                getDDLCreateTable("executor", ImmutableList.of(
                        new VarcharColumnDef("discriminator", 1, false),
                        new BigintColumnDef("id", false).setPrimaryKey(),
                        new TimestampColumnDef("create_date", false),
                        new BigintColumnDef("version", true),
                        new VarcharColumnDef("description", 1024, true),
                        new VarcharColumnDef("full_name", 1024, true),
                        new VarcharColumnDef("name", 1024, false),
                        new VarcharColumnDef("e_mail", 255, true),
                        new BigintColumnDef("process_id", true),
                        new VarcharColumnDef("phone", 1024, true),
                        new VarcharColumnDef("department", 1024, true),
                        new VarcharColumnDef("title", 1024, true),
                        new BigintColumnDef("code", true),
                        new BooleanColumnDef("is_active", true),
                        new VarcharColumnDef("node_id", 1024, true),
                        new IntColumnDef("escalation_level", true),
                        new BigintColumnDef("escalation_executor_id", true)
                )),
                getDDLCreateTable("executor_group_member", ImmutableList.of(
                        new BigintColumnDef("id", false).setPrimaryKey(),
                        new TimestampColumnDef("create_date", false),
                        new BigintColumnDef("version", true),
                        new BigintColumnDef("group_id", false),
                        new BigintColumnDef("executor_id", false)
                )),
                getDDLCreateTable("executor_relation", ImmutableList.of(
                        new BigintColumnDef("id", false).setPrimaryKey(),
                        new TimestampColumnDef("create_date", false),
                        new VarcharColumnDef("description", 1024, true),
                        new VarcharColumnDef("name", 1024, true)
                )),
                getDDLCreateTable("executor_relation_pair", ImmutableList.of(
                        new BigintColumnDef("id", false).setPrimaryKey(),
                        new TimestampColumnDef("create_date", false),
                        new BigintColumnDef("executor_from", false),
                        new BigintColumnDef("relation_id", false),
                        new BigintColumnDef("executor_to", false)
                )),
                getDDLCreateTable("localization", ImmutableList.of(
                        new BigintColumnDef("id", false).setPrimaryKey(),
                        new TimestampColumnDef("create_date", false),
                        new VarcharColumnDef("name", 1024, true),
                        new VarcharColumnDef("value", 1024, true)
                )),
                getDDLCreateTable("permission_mapping", ImmutableList.of(
                        new BigintColumnDef("id", false).setPrimaryKey(),
                        new VarcharColumnDef("object_type", 255, false),
                        new BigintColumnDef("object_id", false),
                        new VarcharColumnDef("permission", 255, false),
                        new BigintColumnDef("executor_id", false)
                )),
                getDDLCreateTable("priveleged_mapping", ImmutableList.of(
                        new BigintColumnDef("id", false).setPrimaryKey(),
                        new VarcharColumnDef("type", 1024, false),
                        new BigintColumnDef("executor_id", false)
                )),
                getDDLCreateTable("profile", ImmutableList.of(
                        new BigintColumnDef("id", false).setPrimaryKey(),
                        new TimestampColumnDef("create_date", false),
                        new BigintColumnDef("version", true),
                        new BigintColumnDef("actor_id", false)
                )),
                getDDLCreateTable("report", ImmutableList.of(
                        new BigintColumnDef("id", false).setPrimaryKey(),
                        new VarcharColumnDef("category", 1024, true),
                        new BlobColumnDef("compiled_report", false),
                        new VarcharColumnDef("config_type", 1024, false),
                        new BigintColumnDef("version", false),
                        new VarcharColumnDef("description", 2048, true),
                        new VarcharColumnDef("name", 1024, false)
                )),
                getDDLCreateTable("report_parameter", ImmutableList.of(
                        new BigintColumnDef("id", false).setPrimaryKey(),
                        new VarcharColumnDef("inner_name", 1024, false),
                        new BooleanColumnDef("required", false),
                        new VarcharColumnDef("name", 1024, false),
                        new VarcharColumnDef("type", 1024, false),
                        new BigintColumnDef("report_id", false)
                )),
                getDDLCreateTable("substitution", ImmutableList.of(
                        new VarcharColumnDef("discriminator", 1, false),
                        new BigintColumnDef("id", false).setPrimaryKey(),
                        new BigintColumnDef("actor_id", false),
                        new VarcharColumnDef("org_function", 1024, false),
                        new TimestampColumnDef("create_date", false),
                        new BooleanColumnDef("is_external", false),
                        new BigintColumnDef("version", true),
                        new IntColumnDef("position_index", false),
                        new BooleanColumnDef("enabled_flag", false),
                        new BigintColumnDef("criteria_id", true)
                )),
                getDDLCreateTable("substitution_criteria", ImmutableList.of(
                        new VarcharColumnDef("discriminator", 31, false),
                        new BigintColumnDef("id", false).setPrimaryKey(),
                        new TimestampColumnDef("create_date", false),
                        new VarcharColumnDef("conf", 1024, true),
                        new VarcharColumnDef("name", 1024, false)
                )),
                getDDLCreateTable("system_log", ImmutableList.of(
                        new VarcharColumnDef("discriminator", 31, false),
                        new BigintColumnDef("id", false).setPrimaryKey(),
                        new BigintColumnDef("actor_id", false),
                        new TimestampColumnDef("create_date", false),
                        new BigintColumnDef("process_id", true),
                        new VarcharColumnDef("process_definition_name", 1024, true),
                        new BigintColumnDef("process_definition_version", true)
                )),
                getDDLCreateTable("wfe_constants", ImmutableList.of(
                        new BigintColumnDef("id", false).setPrimaryKey(),
                        new VarcharColumnDef("name", 1024, true),
                        new VarcharColumnDef("value", 1024, true)
                )),
                getDDLCreateIndex("archived_log", "ix_arch_log_process", "process_id"),
                getDDLCreateIndex("archived_process", "ix_arch_process_def_ver", "definition_version_id"),
                getDDLCreateIndex("archived_process", "ix_arch_process_root_token", "root_token_id"),
                getDDLCreateIndex("archived_subprocess", "ix_arch_subprocess_parent", "parent_process_id"),
                getDDLCreateIndex("archived_subprocess", "ix_arch_subprocess_process", "process_id"),
                getDDLCreateIndex("archived_subprocess", "ix_arch_subprocess_root", "root_process_id"),
                getDDLCreateIndex("archived_swimlane", "ix_arch_swimlane_process", "process_id"),
                getDDLCreateIndex("archived_token", "ix_arch_message_selector", "message_selector"),
                getDDLCreateIndex("archived_token", "ix_arch_token_parent", "parent_id"),
                getDDLCreateIndex("archived_token", "ix_arch_token_process", "process_id"),
                getDDLCreateIndex("archived_variable", "ix_arch_variable_name", "name"),
                getDDLCreateIndex("archived_variable", "ix_arch_variable_process", "process_id"),
                getDDLCreateIndex("batch_presentation", "ix_batch_presentation_profile", "profile_id"),
                getDDLCreateIndex("bot", "ix_bot_station", "bot_station_id"),
                getDDLCreateIndex("bot_task", "ix_bot_task_bot", "bot_id"),
                getDDLCreateIndex("bpm_agglog_assignments", "ix_agglog_assign_date", "assignment_date"),
                getDDLCreateIndex("bpm_agglog_assignments", "ix_agglog_assign_executor", "new_executor_name"),
                getDDLCreateIndex("bpm_agglog_process", "ix_agglog_process_create_date", "create_date"),
                getDDLCreateIndex("bpm_agglog_process", "ix_agglog_process_end_date", "end_date"),
                getDDLCreateIndex("bpm_agglog_process", "ix_agglog_process_instance", "process_id"),
                getDDLCreateIndex("bpm_agglog_tasks", "ix_agglog_tasks_create_date", "create_date"),
                getDDLCreateIndex("bpm_agglog_tasks", "ix_agglog_tasks_end_date", "end_date"),
                getDDLCreateIndex("bpm_agglog_tasks", "ix_agglog_tasks_process", "process_id"),
                getDDLCreateIndex("bpm_job", "ix_job_process", "process_id"),
                getDDLCreateIndex("bpm_log", "ix_log_process", "process_id"),
                getDDLCreateIndex("bpm_process", "ix_process_definition_ver", "definition_version_id"),
                getDDLCreateIndex("bpm_process", "ix_process_root_token", "root_token_id"),
                getDDLCreateIndex("bpm_subprocess", "ix_subprocess_parent_process", "parent_process_id"),
                getDDLCreateIndex("bpm_subprocess", "ix_subprocess_process", "process_id"),
                getDDLCreateIndex("bpm_subprocess", "ix_subprocess_root_process", "root_process_id"),
                getDDLCreateIndex("bpm_swimlane", "ix_swimlane_process", "process_id"),
                getDDLCreateIndex("bpm_task", "ix_task_executor", "executor_id"),
                getDDLCreateIndex("bpm_task", "ix_task_process", "process_id"),
                getDDLCreateIndex("bpm_token", "ix_message_selector", "message_selector"),
                getDDLCreateIndex("bpm_token", "ix_token_parent", "parent_id"),
                getDDLCreateIndex("bpm_token", "ix_token_process", "process_id"),
                getDDLCreateIndex("bpm_variable", "ix_variable_name", "name"),
                getDDLCreateIndex("bpm_variable", "ix_variable_process", "process_id"),
                getDDLCreateIndex("executor", "ix_executor_code", "code"),
                getDDLCreateIndex("executor_group_member", "ix_member_executor", "executor_id"),
                getDDLCreateIndex("executor_group_member", "ix_member_group", "group_id"),
                getDDLCreateIndex("executor_relation_pair", "ix_erp_executor_from", "executor_from"),
                getDDLCreateIndex("executor_relation_pair", "ix_erp_executor_to", "executor_to"),
                getDDLCreateIndex("executor_relation_pair", "ix_erp_relation", "relation_id"),
                getDDLCreateIndex("permission_mapping", "ix_permission_mapping_data", "executor_id", "object_type", "permission", "object_id"),
                getDDLCreateIndex("priveleged_mapping", "ix_privelege_type", "type"),
                getDDLCreateIndex("substitution", "ix_substitution_actor", "actor_id"),
                getDDLCreateIndex("substitution", "ix_substitution_criteria", "criteria_id"),
                getDDLCreateUniqueKey("archived_variable", "archived_variable_process_id_name_key", "process_id", "name"),
                getDDLCreateUniqueKey("bot_station", "bot_station_name_key", "name"),
                getDDLCreateUniqueKey("bpm_variable", "bpm_variable_process_id_name_key", "process_id", "name"),
                getDDLCreateUniqueKey("executor", "executor_name_key", "name"),
                getDDLCreateUniqueKey("executor_group_member", "executor_group_member_executor_id_group_id_key", "executor_id", "group_id"),
                getDDLCreateUniqueKey("executor_relation", "executor_relation_name_key", "name"),
                getDDLCreateUniqueKey("localization", "localization_name_key", "name"),
                getDDLCreateUniqueKey("permission_mapping", "permission_mapping_object_id_object_type_permission_executo_key", "object_id", "object_type", "permission", "executor_id"),
                getDDLCreateUniqueKey("profile", "profile_actor_id_key", "actor_id"),
                getDDLCreateUniqueKey("report", "report_name_key", "name"),
                getDDLCreateUniqueKey("substitution", "substitution_position_index_actor_id_key", "position_index", "actor_id"),
                getDDLCreateUniqueKey("wfe_constants", "wfe_constants_name_key", "name"),
                getDDLCreateForeignKey("archived_process", "fk_arch_process_def_ver", "definition_version_id", "bpm_process_definition_ver", "id"),
                getDDLCreateForeignKey("archived_subprocess", "fk_arch_subprocess_parent", "parent_process_id", "archived_process", "id"),
                getDDLCreateForeignKey("archived_subprocess", "fk_arch_subprocess_process", "process_id", "archived_process", "id"),
                getDDLCreateForeignKey("archived_subprocess", "fk_arch_subprocess_root", "root_process_id", "archived_process", "id"),
                getDDLCreateForeignKey("archived_swimlane", "fk_arch_swimlane_executor", "executor_id", "executor", "id"),
                getDDLCreateForeignKey("archived_swimlane", "fk_arch_swimlane_process", "process_id", "archived_process", "id"),
                getDDLCreateForeignKey("archived_token", "fk_arch_token_process", "process_id", "archived_process", "id"),
                getDDLCreateForeignKey("archived_token", "fkcec15b3c25be6cac", "parent_id", "archived_token", "id"),
                getDDLCreateForeignKey("archived_variable", "fk_arch_variable_process", "process_id", "archived_process", "id"),
                getDDLCreateForeignKey("batch_presentation", "fk_batch_presentation_profile", "profile_id", "profile", "id"),
                getDDLCreateForeignKey("bot", "fk_bot_station", "bot_station_id", "bot_station", "id"),
                getDDLCreateForeignKey("bot_task", "fk_bot_task_bot", "bot_id", "bot", "id"),
                getDDLCreateForeignKey("bpm_agglog_assignments", "fkbe3af20a436bb212", "assignment_object_id", "bpm_agglog_tasks", "id"),
                getDDLCreateForeignKey("bpm_job", "fk_job_process", "process_id", "bpm_process", "id"),
                getDDLCreateForeignKey("bpm_job", "fk_job_token", "token_id", "bpm_token", "id"),
                getDDLCreateForeignKey("bpm_process", "fk_process_definition_ver", "definition_version_id", "bpm_process_definition_ver", "id"),
                getDDLCreateForeignKey("bpm_process", "fk_process_root_token", "root_token_id", "bpm_token", "id"),
                getDDLCreateForeignKey("bpm_process_definition_ver", "fk_definition_create_user", "create_user_id", "executor", "id"),
                getDDLCreateForeignKey("bpm_process_definition_ver", "fk_definition_update_user", "update_user_id", "executor", "id"),
                getDDLCreateForeignKey("bpm_process_definition_ver", "fk_version_definition", "definition_id", "bpm_process_definition", "id"),
                getDDLCreateForeignKey("bpm_subprocess", "fk_subprocess_parent_process", "parent_process_id", "bpm_process", "id"),
                getDDLCreateForeignKey("bpm_subprocess", "fk_subprocess_process", "process_id", "bpm_process", "id"),
                getDDLCreateForeignKey("bpm_subprocess", "fk_subprocess_root_process", "root_process_id", "bpm_process", "id"),
                getDDLCreateForeignKey("bpm_subprocess", "fk_subprocess_token", "parent_token_id", "bpm_token", "id"),
                getDDLCreateForeignKey("bpm_swimlane", "fk_swimlane_executor", "executor_id", "executor", "id"),
                getDDLCreateForeignKey("bpm_swimlane", "fk_swimlane_process", "process_id", "bpm_process", "id"),
                getDDLCreateForeignKey("bpm_task", "fk_task_executor", "executor_id", "executor", "id"),
                getDDLCreateForeignKey("bpm_task", "fk_task_process", "process_id", "bpm_process", "id"),
                getDDLCreateForeignKey("bpm_task", "fk_task_swimlane", "swimlane_id", "bpm_swimlane", "id"),
                getDDLCreateForeignKey("bpm_task", "fk_task_token", "token_id", "bpm_token", "id"),
                getDDLCreateForeignKey("bpm_task_opened", "fk_task_opened_task", "task_id", "bpm_task", "id"),
                getDDLCreateForeignKey("bpm_token", "fk_token_parent", "parent_id", "bpm_token", "id"),
                getDDLCreateForeignKey("bpm_token", "fk_token_process", "process_id", "bpm_process", "id"),
                getDDLCreateForeignKey("bpm_variable", "fk_variable_process", "process_id", "bpm_process", "id"),
                getDDLCreateForeignKey("executor", "fk_group_escalation_executor", "escalation_executor_id", "executor", "id"),
                getDDLCreateForeignKey("executor_group_member", "fk_member_executor", "executor_id", "executor", "id"),
                getDDLCreateForeignKey("executor_group_member", "fk_member_group", "group_id", "executor", "id"),
                getDDLCreateForeignKey("executor_relation_pair", "fk_erp_executor_from", "executor_from", "executor", "id"),
                getDDLCreateForeignKey("executor_relation_pair", "fk_erp_executor_to", "executor_to", "executor", "id"),
                getDDLCreateForeignKey("executor_relation_pair", "fk_erp_relation", "relation_id", "executor_relation", "id"),
                getDDLCreateForeignKey("permission_mapping", "fk_permission_executor", "executor_id", "executor", "id"),
                getDDLCreateForeignKey("priveleged_mapping", "fk_pm_executor", "executor_id", "executor", "id"),
                getDDLCreateForeignKey("profile", "fk_profile_actor", "actor_id", "executor", "id"),
                getDDLCreateForeignKey("report_parameter", "fkbc64163ec3ead862", "report_id", "report", "id"),
                getDDLCreateForeignKey("substitution", "fk_substitution_criteria", "criteria_id", "substitution_criteria", "id")
        );
    }

    @Override
    public void executeDML(Connection conn) throws Exception {
        try (PreparedStatement stmt = conn.prepareStatement("insert into db_migration(name, when_started_when_finished) values(?, ?, ?)")) {
            insertMigration(stmt, "AddAggregatedTaskIndexPatch", 1537198105884L, 1537198105884L);
            insertMigration(stmt, "AddAssignDateColumnPatch", 1537198105884L, 1537198105884L);
            insertMigration(stmt, "AddBatchPresentationIsSharedPatch", 1537198105884L, 1537198105884L);
            insertMigration(stmt, "AddColumnForEmbeddedBotTaskFileName", 1537198105884L, 1537198105884L);
            insertMigration(stmt, "AddColumnsToSubstituteEscalatedTasksPatch", 1537198105884L, 1537198105884L);
            insertMigration(stmt, "AddCreateDateColumns", 1537198105884L, 1537198105884L);
            insertMigration(stmt, "AddDeploymentAuditPatch", 1537198105884L, 1537198105884L);
            insertMigration(stmt, "AddDueDateExpressionToJobAndTask", 1537198105884L, 1537198105884L);
            insertMigration(stmt, "AddEmbeddedFileForBotTask", 1537198105884L, 1537198105884L);
            insertMigration(stmt, "AddHierarchyProcess", 1537198105884L, 1537198105884L);
            insertMigration(stmt, "AddMultiTaskIndexToTaskPatch", 1537198105884L, 1537198105884L);
            insertMigration(stmt, "AddNodeIdToProcessLogPatch", 1537198105884L, 1537198105884L);
            insertMigration(stmt, "AddParentProcessIdPatch", 1537198105884L, 1537198105884L);
            insertMigration(stmt, "AddProcessAndTokenExecutionStatusPatch", 1537198105884L, 1537198105884L);
            insertMigration(stmt, "AddSequentialFlagToBot", 1537198105884L, 1537198105884L);
            insertMigration(stmt, "AddSettingsTable", 1537198105884L, 1537198105884L);
            insertMigration(stmt, "AddSubprocessBindingDatePatch", 1537198105884L, 1537198105884L);
            insertMigration(stmt, "AddSubProcessIndexColumn", 1537198105884L, 1537198105884L);
            insertMigration(stmt, "AddSubprocessRootIdColumn", 1537198105884L, 1537198105884L);
            insertMigration(stmt, "AddTitleAndDepartmentColumnsToActorPatch", 1537198105884L, 1537198105884L);
            insertMigration(stmt, "AddTokenErrorDataPatch", 1537198105884L, 1537198105884L);
            insertMigration(stmt, "AddTokenMessageSelectorPatch", 1537198105884L, 1537198105884L);
            insertMigration(stmt, "AddTransactionalBotSupport", 1537198105884L, 1537198105884L);
            insertMigration(stmt, "AddVariableUniqueKeyPatch", 1537198105884L, 1537198105884L);
            insertMigration(stmt, "CreateAdminScriptTables", 1537198105884L, 1537198105884L);
            insertMigration(stmt, "CreateAggregatedLogsTables", 1537198105884L, 1537198105884L);
            insertMigration(stmt, "CreateReportsTables", 1537198105884L, 1537198105884L);
            insertMigration(stmt, "ExpandDescriptionsPatch", 1537198105884L, 1537198105884L);
            insertMigration(stmt, "ExpandVarcharPatch", 1537198105884L, 1537198105884L);
            insertMigration(stmt, "JbpmRefactoringPatch", 1537198105884L, 1537198105884L);
            insertMigration(stmt, "NodeTypeChangePatch", 1537198105884L, 1537198105884L);
            insertMigration(stmt, "PerformancePatch401", 1537198105884L, 1537198105884L);
            insertMigration(stmt, "PermissionMappingPatch403", 1537198105884L, 1537198105884L);
            insertMigration(stmt, "RefactorPermissionsStep1", 1537198105884L, 1537198105884L);
            insertMigration(stmt, "RefactorPermissionsStep3", 1537198105884L, 1537198105884L);
            insertMigration(stmt, "RenameProcessesBatchPresentationCategories", 1537198105884L, 1537198105884L);
            insertMigration(stmt, "SplitProcessDefinitionVersion", 1537198105884L, 1537198105884L);
            insertMigration(stmt, "SupportProcessArchiving", 1537198105884L, 1537198105884L);
            insertMigration(stmt, "TaskCreateLogSeverityChangedPatch", 1537198105884L, 1537198105884L);
            insertMigration(stmt, "TaskEndDateRemovalPatch", 1537198105884L, 1537198105884L);
            insertMigration(stmt, "TaskOpenedByExecutorsPatch", 1537198105884L, 1537198105884L);
            insertMigration(stmt, "TransitionLogPatch", 1537198105884L, 1537198105884L);
        }
    }

    private void insertMigration(PreparedStatement stmt, String name, long whenStarted, Long whenFinished) throws Exception {
        stmt.setString(1, name);
        stmt.setTimestamp(2, new Timestamp(whenStarted));
        stmt.setTimestamp(3, whenFinished == null ? null : new Timestamp(whenFinished));
        stmt.executeUpdate();
    }
}
