//
// ATTENTION!!! This file is auto-generated by wfe-codegen-dbaware subproject. See README.txt there.
//
package ru.runa.wfe.commons.dbpatch;

import com.google.common.collect.ImmutableList;
import java.sql.Connection;
import java.util.List;

public class DbPatch0 extends DbPatch {

    @Override
    protected List<String> getDDLQueriesBefore() {
        return ImmutableList.of(
                getDDLCreateTable("actor_password", ImmutableList.of(
                        new BigintColumnDef("actor_id", false).setPrimaryKey(),
                        new BlobColumnDef("password", false)
                )),
                getDDLCreateTable("admin_script", ImmutableList.of(
                        new BigintColumnDef("id", false).setPrimaryKey(),
                        new VarcharColumnDef("name", 1024, true),
                        new BlobColumnDef("content", true)
                )),
                getDDLCreateTable("archived_log", ImmutableList.of(
                        new CharColumnDef("discriminator", 1, false),
                        new BigintColumnDef("id", false).setPrimaryKey(),
                        new VarcharColumnDef("severity", 1024, false),
                        new BigintColumnDef("token_id", true),
                        new VarcharColumnDef("node_id", 1024, true),
                        new TimestampColumnDef("create_date", false),
                        new BlobColumnDef("bytes", true),
                        new VarcharColumnDef("content", 4000, true),
                        new BigintColumnDef("process_id", false)
                )),
                getDDLCreateTable("archived_process", ImmutableList.of(
                        new BigintColumnDef("id", false).setPrimaryKey(),
                        new BigintColumnDef("parent_id", true),
                        new BigintColumnDef("version", true),
                        new VarcharColumnDef("tree_path", 1024, true),
                        new TimestampColumnDef("start_date", true),
                        new TimestampColumnDef("end_date", true),
                        new BigintColumnDef("root_token_id", false),
                        new BigintColumnDef("definition_version_id", false)
                )),
                getDDLCreateTable("archived_subprocess", ImmutableList.of(
                        new BigintColumnDef("id", false).setPrimaryKey(),
                        new VarcharColumnDef("parent_node_id", 1024, true),
                        new IntColumnDef("subprocess_index", true),
                        new TimestampColumnDef("create_date", false),
                        new BigintColumnDef("process_id", false),
                        new BigintColumnDef("parent_token_id", true),
                        new BigintColumnDef("root_process_id", false),
                        new BigintColumnDef("parent_process_id", false)
                )),
                getDDLCreateTable("archived_swimlane", ImmutableList.of(
                        new BigintColumnDef("id", false).setPrimaryKey(),
                        new BigintColumnDef("version", true),
                        new VarcharColumnDef("name", 1024, true),
                        new TimestampColumnDef("create_date", false),
                        new BigintColumnDef("process_id", true),
                        new BigintColumnDef("executor_id", true)
                )),
                getDDLCreateTable("archived_token", ImmutableList.of(
                        new BigintColumnDef("id", false).setPrimaryKey(),
                        new BigintColumnDef("version", true),
                        new VarcharColumnDef("name", 1024, true),
                        new VarcharColumnDef("node_type", 1024, true),
                        new VarcharColumnDef("node_id", 1024, true),
                        new VarcharColumnDef("transition_id", 1024, true),
                        new TimestampColumnDef("start_date", true),
                        new TimestampColumnDef("end_date", true),
                        new BooleanColumnDef("reactivate_parent", true),
                        new TimestampColumnDef("error_date", true),
                        new VarcharColumnDef("error_message", 1024, true),
                        new VarcharColumnDef("message_selector", 1024, true),
                        new BigintColumnDef("parent_id", true),
                        new BigintColumnDef("process_id", true)
                )),
                getDDLCreateTable("archived_variable", ImmutableList.of(
                        new CharColumnDef("discriminator", 1, false),
                        new BigintColumnDef("id", false).setPrimaryKey(),
                        new VarcharColumnDef("stringvalue", 1024, true),
                        new TimestampColumnDef("create_date", false),
                        new CharColumnDef("converter", 1, true),
                        new BigintColumnDef("version", true),
                        new VarcharColumnDef("name", 1024, true),
                        new BlobColumnDef("bytes", true),
                        new BigintColumnDef("longvalue", true),
                        new DoubleColumnDef("doublevalue", true),
                        new TimestampColumnDef("datevalue", true),
                        new BigintColumnDef("process_id", false)
                )),
                getDDLCreateTable("batch_presentation", ImmutableList.of(
                        new BigintColumnDef("id", false).setPrimaryKey(),
                        new VarcharColumnDef("category", 1024, false),
                        new BlobColumnDef("fields", true),
                        new IntColumnDef("range_size", true),
                        new TimestampColumnDef("create_date", false),
                        new BigintColumnDef("version", true),
                        new BooleanColumnDef("shared", false),
                        new BooleanColumnDef("is_active", true),
                        new VarcharColumnDef("name", 1024, false),
                        new VarcharColumnDef("class_type", 1024, true),
                        new BigintColumnDef("profile_id", true)
                )),
                getDDLCreateTable("bot", ImmutableList.of(
                        new BigintColumnDef("id", false).setPrimaryKey(),
                        new BooleanColumnDef("is_transactional", true),
                        new VarcharColumnDef("password", 1024, true),
                        new BooleanColumnDef("is_sequential", true),
                        new BigintColumnDef("transactional_timeout", true),
                        new TimestampColumnDef("bound_due_date", true),
                        new BigintColumnDef("bound_process_id", true),
                        new VarcharColumnDef("bound_subprocess_id", 255, true),
                        new VarcharColumnDef("username", 1024, true),
                        new TimestampColumnDef("create_date", false),
                        new BigintColumnDef("version", true),
                        new BigintColumnDef("bot_station_id", false)
                )),
                getDDLCreateTable("bot_station", ImmutableList.of(
                        new BigintColumnDef("id", false).setPrimaryKey(),
                        new BigintColumnDef("version", true),
                        new VarcharColumnDef("name", 1024, false),
                        new VarcharColumnDef("address", 1024, true),
                        new TimestampColumnDef("create_date", false)
                )),
                getDDLCreateTable("bot_task", ImmutableList.of(
                        new BigintColumnDef("id", false).setPrimaryKey(),
                        new BlobColumnDef("embedded_file", true),
                        new VarcharColumnDef("embedded_file_name", 1024, true),
                        new BooleanColumnDef("is_sequential", true),
                        new VarcharColumnDef("task_handler", 1024, true),
                        new TimestampColumnDef("create_date", false),
                        new BigintColumnDef("version", true),
                        new BlobColumnDef("configuration", true),
                        new VarcharColumnDef("name", 1024, true),
                        new BigintColumnDef("bot_id", false)
                )),
                getDDLCreateTable("bpm_agglog_assignments", ImmutableList.of(
                        new CharColumnDef("discriminator", 1, false),
                        new BigintColumnDef("id", false).setPrimaryKey(),
                        new TimestampColumnDef("assignment_date", false),
                        new VarcharColumnDef("new_executor_name", 1024, true),
                        new VarcharColumnDef("old_executor_name", 1024, true),
                        new BigintColumnDef("assignment_object_id", true),
                        new IntColumnDef("idx", true)
                )),
                getDDLCreateTable("bpm_agglog_process", ImmutableList.of(
                        new BigintColumnDef("id", false).setPrimaryKey(),
                        new VarcharColumnDef("cancel_actor_name", 1024, true),
                        new BigintColumnDef("process_id", false),
                        new BigintColumnDef("parent_process_id", true),
                        new VarcharColumnDef("start_actor_name", 1024, true),
                        new TimestampColumnDef("end_date", true),
                        new IntColumnDef("end_reason", false),
                        new TimestampColumnDef("create_date", false)
                )),
                getDDLCreateTable("bpm_agglog_tasks", ImmutableList.of(
                        new BigintColumnDef("id", false).setPrimaryKey(),
                        new VarcharColumnDef("task_name", 1024, false),
                        new BigintColumnDef("task_id", false),
                        new BigintColumnDef("token_id", false),
                        new VarcharColumnDef("swimlane_name", 1024, true),
                        new TimestampColumnDef("deadline_date", true),
                        new TimestampColumnDef("end_date", true),
                        new VarcharColumnDef("initial_actor_name", 1024, true),
                        new VarcharColumnDef("complete_actor_name", 1024, true),
                        new IntColumnDef("end_reason", false),
                        new VarcharColumnDef("node_id", 1024, false),
                        new IntColumnDef("task_index", true),
                        new TimestampColumnDef("create_date", false),
                        new BigintColumnDef("process_id", false)
                )),
                getDDLCreateTable("bpm_job", ImmutableList.of(
                        new CharColumnDef("discriminator", 1, false),
                        new BigintColumnDef("id", false).setPrimaryKey(),
                        new TimestampColumnDef("due_date", true),
                        new VarcharColumnDef("due_date_expression", 255, true),
                        new TimestampColumnDef("create_date", false),
                        new BigintColumnDef("version", true),
                        new VarcharColumnDef("name", 1024, true),
                        new VarcharColumnDef("repeat_duration", 1024, true),
                        new VarcharColumnDef("transition_name", 1024, true),
                        new BigintColumnDef("process_id", false),
                        new BigintColumnDef("token_id", true)
                )),
                getDDLCreateTable("bpm_log", ImmutableList.of(
                        new CharColumnDef("discriminator", 1, false),
                        new BigintColumnDef("id", false).setPrimaryKey(),
                        new VarcharColumnDef("severity", 1024, false),
                        new BigintColumnDef("token_id", true),
                        new VarcharColumnDef("node_id", 1024, true),
                        new TimestampColumnDef("create_date", false),
                        new BlobColumnDef("bytes", true),
                        new VarcharColumnDef("content", 4000, true),
                        new BigintColumnDef("process_id", false)
                )),
                getDDLCreateTable("bpm_process", ImmutableList.of(
                        new BigintColumnDef("id", false).setPrimaryKey(),
                        new BigintColumnDef("parent_id", true),
                        new BigintColumnDef("version", true),
                        new VarcharColumnDef("tree_path", 1024, true),
                        new TimestampColumnDef("start_date", true),
                        new TimestampColumnDef("end_date", true),
                        new VarcharColumnDef("execution_status", 255, false),
                        new BigintColumnDef("definition_version_id", false),
                        new BigintColumnDef("root_token_id", false)
                )),
                getDDLCreateTable("bpm_process_definition", ImmutableList.of(
                        new BigintColumnDef("id", false).setPrimaryKey(),
                        new IntColumnDef("seconds_before_archiving", true),
                        new VarcharColumnDef("category", 1024, false),
                        new VarcharColumnDef("description", 1024, true),
                        new VarcharColumnDef("name", 1024, false),
                        new VarcharColumnDef("language", 4, false),
                        new BigintColumnDef("latest_version_id", true)
                )),
                getDDLCreateTable("bpm_process_definition_ver", ImmutableList.of(
                        new BigintColumnDef("id", false).setPrimaryKey(),
                        new BigintColumnDef("subversion", false),
                        new TimestampColumnDef("subprocess_binding_date", true),
                        new TimestampColumnDef("update_date", true),
                        new TimestampColumnDef("create_date", false),
                        new BigintColumnDef("version", false),
                        new BlobColumnDef("bytes", true),
                        new BigintColumnDef("create_user_id", true),
                        new BigintColumnDef("update_user_id", true),
                        new BigintColumnDef("definition_id", false)
                )),
                getDDLCreateTable("bpm_setting", ImmutableList.of(
                        new BigintColumnDef("id", false).setPrimaryKey(),
                        new VarcharColumnDef("name", 1024, false),
                        new VarcharColumnDef("value", 1024, true),
                        new VarcharColumnDef("file_name", 1024, false)
                )),
                getDDLCreateTable("bpm_subprocess", ImmutableList.of(
                        new BigintColumnDef("id", false).setPrimaryKey(),
                        new VarcharColumnDef("parent_node_id", 1024, true),
                        new IntColumnDef("subprocess_index", true),
                        new TimestampColumnDef("create_date", false),
                        new BigintColumnDef("parent_token_id", true),
                        new BigintColumnDef("process_id", false),
                        new BigintColumnDef("parent_process_id", false),
                        new BigintColumnDef("root_process_id", false)
                )),
                getDDLCreateTable("bpm_swimlane", ImmutableList.of(
                        new BigintColumnDef("id", false).setPrimaryKey(),
                        new BigintColumnDef("version", true),
                        new VarcharColumnDef("name", 1024, true),
                        new TimestampColumnDef("create_date", false),
                        new BigintColumnDef("executor_id", true),
                        new BigintColumnDef("process_id", true)
                )),
                getDDLCreateTable("bpm_task", ImmutableList.of(
                        new BigintColumnDef("id", false).setPrimaryKey(),
                        new TimestampColumnDef("deadline_date", true),
                        new TimestampColumnDef("assign_date", true),
                        new VarcharColumnDef("deadline_date_expression", 255, true),
                        new VarcharColumnDef("node_id", 1024, true),
                        new TimestampColumnDef("create_date", false),
                        new BigintColumnDef("version", true),
                        new IntColumnDef("task_index", true),
                        new VarcharColumnDef("description", 1024, true),
                        new VarcharColumnDef("name", 1024, true),
                        new BigintColumnDef("process_id", true),
                        new BigintColumnDef("executor_id", true),
                        new BigintColumnDef("token_id", true),
                        new BigintColumnDef("swimlane_id", true)
                )),
                getDDLCreateTable("bpm_task_opened", ImmutableList.of(
                        new BigintColumnDef("task_id", false),
                        new BigintColumnDef("executor_id", true)
                )),
                getDDLCreateTable("bpm_token", ImmutableList.of(
                        new BigintColumnDef("id", false).setPrimaryKey(),
                        new BigintColumnDef("version", true),
                        new VarcharColumnDef("name", 1024, true),
                        new VarcharColumnDef("node_type", 1024, true),
                        new VarcharColumnDef("node_id", 1024, true),
                        new VarcharColumnDef("transition_id", 1024, true),
                        new TimestampColumnDef("start_date", true),
                        new TimestampColumnDef("end_date", true),
                        new BooleanColumnDef("reactivate_parent", true),
                        new TimestampColumnDef("error_date", true),
                        new VarcharColumnDef("error_message", 1024, true),
                        new VarcharColumnDef("execution_status", 255, false),
                        new VarcharColumnDef("message_selector", 1024, true),
                        new BigintColumnDef("process_id", true),
                        new BigintColumnDef("parent_id", true)
                )),
                getDDLCreateTable("bpm_variable", ImmutableList.of(
                        new CharColumnDef("discriminator", 1, false),
                        new BigintColumnDef("id", false).setPrimaryKey(),
                        new VarcharColumnDef("stringvalue", 1024, true),
                        new TimestampColumnDef("create_date", false),
                        new CharColumnDef("converter", 1, true),
                        new BigintColumnDef("version", true),
                        new VarcharColumnDef("name", 1024, true),
                        new TimestampColumnDef("datevalue", true),
                        new BigintColumnDef("longvalue", true),
                        new BlobColumnDef("bytes", true),
                        new DoubleColumnDef("doublevalue", true),
                        new BigintColumnDef("process_id", false)
                )),
                getDDLCreateTable("db_migration", ImmutableList.of(
                        new VarcharColumnDef("name", 255, false).setPrimaryKey(),
                        new TimestampColumnDef("when_started", false),
                        new TimestampColumnDef("when_finished", true)
                )),
                getDDLCreateTable("executor", ImmutableList.of(
                        new VarcharColumnDef("discriminator", 1, false),
                        new BigintColumnDef("id", false).setPrimaryKey(),
                        new TimestampColumnDef("create_date", false),
                        new BigintColumnDef("version", true),
                        new VarcharColumnDef("description", 1024, true),
                        new VarcharColumnDef("full_name", 1024, true),
                        new VarcharColumnDef("name", 1024, false),
                        new VarcharColumnDef("e_mail", 255, true),
                        new BigintColumnDef("process_id", true),
                        new VarcharColumnDef("phone", 1024, true),
                        new VarcharColumnDef("department", 1024, true),
                        new VarcharColumnDef("title", 1024, true),
                        new BigintColumnDef("code", true),
                        new BooleanColumnDef("is_active", true),
                        new VarcharColumnDef("node_id", 1024, true),
                        new IntColumnDef("escalation_level", true),
                        new BigintColumnDef("escalation_executor_id", true)
                )),
                getDDLCreateTable("executor_group_member", ImmutableList.of(
                        new BigintColumnDef("id", false).setPrimaryKey(),
                        new TimestampColumnDef("create_date", false),
                        new BigintColumnDef("version", true),
                        new BigintColumnDef("group_id", false),
                        new BigintColumnDef("executor_id", false)
                )),
                getDDLCreateTable("executor_relation", ImmutableList.of(
                        new BigintColumnDef("id", false).setPrimaryKey(),
                        new TimestampColumnDef("create_date", false),
                        new VarcharColumnDef("description", 1024, true),
                        new VarcharColumnDef("name", 1024, true)
                )),
                getDDLCreateTable("executor_relation_pair", ImmutableList.of(
                        new BigintColumnDef("id", false).setPrimaryKey(),
                        new TimestampColumnDef("create_date", false),
                        new BigintColumnDef("executor_from", false),
                        new BigintColumnDef("relation_id", false),
                        new BigintColumnDef("executor_to", false)
                )),
                getDDLCreateTable("localization", ImmutableList.of(
                        new BigintColumnDef("id", false).setPrimaryKey(),
                        new TimestampColumnDef("create_date", false),
                        new VarcharColumnDef("name", 1024, true),
                        new VarcharColumnDef("value", 1024, true)
                )),
                getDDLCreateTable("permission_mapping", ImmutableList.of(
                        new BigintColumnDef("id", false).setPrimaryKey(),
                        new VarcharColumnDef("object_type", 255, false),
                        new BigintColumnDef("object_id", false),
                        new VarcharColumnDef("permission", 255, false),
                        new BigintColumnDef("executor_id", false)
                )),
                getDDLCreateTable("priveleged_mapping", ImmutableList.of(
                        new BigintColumnDef("id", false).setPrimaryKey(),
                        new VarcharColumnDef("type", 1024, false),
                        new BigintColumnDef("executor_id", false)
                )),
                getDDLCreateTable("profile", ImmutableList.of(
                        new BigintColumnDef("id", false).setPrimaryKey(),
                        new TimestampColumnDef("create_date", false),
                        new BigintColumnDef("version", true),
                        new BigintColumnDef("actor_id", false)
                )),
                getDDLCreateTable("report", ImmutableList.of(
                        new BigintColumnDef("id", false).setPrimaryKey(),
                        new VarcharColumnDef("category", 1024, true),
                        new BlobColumnDef("compiled_report", false),
                        new VarcharColumnDef("config_type", 1024, false),
                        new BigintColumnDef("version", false),
                        new VarcharColumnDef("description", 2048, true),
                        new VarcharColumnDef("name", 1024, false)
                )),
                getDDLCreateTable("report_parameter", ImmutableList.of(
                        new BigintColumnDef("id", false).setPrimaryKey(),
                        new VarcharColumnDef("inner_name", 1024, false),
                        new BooleanColumnDef("required", false),
                        new VarcharColumnDef("name", 1024, false),
                        new VarcharColumnDef("type", 1024, false),
                        new BigintColumnDef("report_id", false)
                )),
                getDDLCreateTable("substitution", ImmutableList.of(
                        new VarcharColumnDef("discriminator", 1, false),
                        new BigintColumnDef("id", false).setPrimaryKey(),
                        new BigintColumnDef("actor_id", false),
                        new VarcharColumnDef("org_function", 1024, false),
                        new TimestampColumnDef("create_date", false),
                        new BooleanColumnDef("is_external", false),
                        new BigintColumnDef("version", true),
                        new IntColumnDef("position_index", false),
                        new BooleanColumnDef("enabled_flag", false),
                        new BigintColumnDef("criteria_id", true)
                )),
                getDDLCreateTable("substitution_criteria", ImmutableList.of(
                        new VarcharColumnDef("discriminator", 31, false),
                        new BigintColumnDef("id", false).setPrimaryKey(),
                        new TimestampColumnDef("create_date", false),
                        new VarcharColumnDef("conf", 1024, true),
                        new VarcharColumnDef("name", 1024, false)
                )),
                getDDLCreateTable("system_log", ImmutableList.of(
                        new VarcharColumnDef("discriminator", 31, false),
                        new BigintColumnDef("id", false).setPrimaryKey(),
                        new BigintColumnDef("actor_id", false),
                        new TimestampColumnDef("create_date", false),
                        new BigintColumnDef("process_id", true),
                        new VarcharColumnDef("process_definition_name", 1024, true),
                        new BigintColumnDef("process_definition_version", true)
                )),
                getDDLCreateTable("wfe_constants", ImmutableList.of(
                        new BigintColumnDef("id", false).setPrimaryKey(),
                        new VarcharColumnDef("name", 1024, true),
                        new VarcharColumnDef("value", 1024, true)
                )),
                getDDLCreateUniqueKey("archived_variable", "archived_variable_process_id_name_key", "process_id", "name"),
                getDDLCreateUniqueKey("bot_station", "bot_station_name_key", "name"),
                getDDLCreateUniqueKey("bpm_variable", "bpm_variable_process_id_name_key", "process_id", "name"),
                getDDLCreateUniqueKey("executor_group_member", "executor_group_member_executor_id_group_id_key", "executor_id", "group_id"),
                getDDLCreateUniqueKey("executor", "executor_name_key", "name"),
                getDDLCreateUniqueKey("executor_relation", "executor_relation_name_key", "name"),
                getDDLCreateUniqueKey("localization", "localization_name_key", "name"),
                getDDLCreateUniqueKey("permission_mapping", "permission_mapping_object_id_object_type_permission_executo_key", "object_id", "object_type", "permission", "executor_id"),
                getDDLCreateUniqueKey("profile", "profile_actor_id_key", "actor_id"),
                getDDLCreateUniqueKey("report", "report_name_key", "name"),
                getDDLCreateUniqueKey("substitution", "substitution_position_index_actor_id_key", "position_index", "actor_id"),
                getDDLCreateUniqueKey("wfe_constants", "wfe_constants_name_key", "name"),
                null
        );
    }

    @Override
    public void executeDML(Connection conn) throws Exception {
    }
}
