
package ru.runa.wfe.webservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2-12/14/2009 02:16 PM(ramkris)-
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "AuthenticationWebService", targetNamespace = "http://impl.service.wfe.runa.ru/", wsdlLocation = "http://localhost:8080/wfe-service-4.3.0-SNAPSHOT/AuthenticationWebService/AuthenticationAPI?wsdl")
public class AuthenticationWebService
    extends Service
{

    private final static URL AUTHENTICATIONWEBSERVICE_WSDL_LOCATION;
    private final static WebServiceException AUTHENTICATIONWEBSERVICE_EXCEPTION;
    private final static QName AUTHENTICATIONWEBSERVICE_QNAME = new QName("http://impl.service.wfe.runa.ru/", "AuthenticationWebService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/wfe-service-4.3.0-SNAPSHOT/AuthenticationWebService/AuthenticationAPI?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        AUTHENTICATIONWEBSERVICE_WSDL_LOCATION = url;
        AUTHENTICATIONWEBSERVICE_EXCEPTION = e;
    }

    public AuthenticationWebService() {
        super(__getWsdlLocation(), AUTHENTICATIONWEBSERVICE_QNAME);
    }

    public AuthenticationWebService(WebServiceFeature... features) {
        super(__getWsdlLocation(), AUTHENTICATIONWEBSERVICE_QNAME, features);
    }

    public AuthenticationWebService(URL wsdlLocation) {
        super(wsdlLocation, AUTHENTICATIONWEBSERVICE_QNAME);
    }

    public AuthenticationWebService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, AUTHENTICATIONWEBSERVICE_QNAME, features);
    }

    public AuthenticationWebService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AuthenticationWebService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns AuthenticationAPI
     */
    @WebEndpoint(name = "AuthenticationAPIPort")
    public AuthenticationAPI getAuthenticationAPIPort() {
        return super.getPort(new QName("http://impl.service.wfe.runa.ru/", "AuthenticationAPIPort"), AuthenticationAPI.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AuthenticationAPI
     */
    @WebEndpoint(name = "AuthenticationAPIPort")
    public AuthenticationAPI getAuthenticationAPIPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://impl.service.wfe.runa.ru/", "AuthenticationAPIPort"), AuthenticationAPI.class, features);
    }

    private static URL __getWsdlLocation() {
        if (AUTHENTICATIONWEBSERVICE_EXCEPTION!= null) {
            throw AUTHENTICATIONWEBSERVICE_EXCEPTION;
        }
        return AUTHENTICATIONWEBSERVICE_WSDL_LOCATION;
    }

}
