
package ru.runa.wfe.webservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2-12/14/2009 02:16 PM(ramkris)-
 * Generated source version: 2.2
 * 
 */
@WebService(name = "AuthenticationAPI", targetNamespace = "http://impl.service.wfe.runa.ru/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface AuthenticationAPI {


    /**
     * 
     * @param token
     * @return
     *     returns ru.runa.wfe.webservice.User
     */
    @WebMethod
    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "authenticateByKerberos", targetNamespace = "http://impl.service.wfe.runa.ru/", className = "ru.runa.wfe.webservice.AuthenticateByKerberos")
    @ResponseWrapper(localName = "authenticateByKerberosResponse", targetNamespace = "http://impl.service.wfe.runa.ru/", className = "ru.runa.wfe.webservice.AuthenticateByKerberosResponse")
    public User authenticateByKerberos(
        @WebParam(name = "token", targetNamespace = "")
        byte[] token);

    /**
     * 
     * @param name
     * @param password
     * @return
     *     returns ru.runa.wfe.webservice.User
     */
    @WebMethod
    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "authenticateByLoginPassword", targetNamespace = "http://impl.service.wfe.runa.ru/", className = "ru.runa.wfe.webservice.AuthenticateByLoginPassword")
    @ResponseWrapper(localName = "authenticateByLoginPasswordResponse", targetNamespace = "http://impl.service.wfe.runa.ru/", className = "ru.runa.wfe.webservice.AuthenticateByLoginPasswordResponse")
    public User authenticateByLoginPassword(
        @WebParam(name = "name", targetNamespace = "")
        String name,
        @WebParam(name = "password", targetNamespace = "")
        String password);

    /**
     * 
     * @param serviceUser
     * @param login
     * @return
     *     returns ru.runa.wfe.webservice.User
     */
    @WebMethod
    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "authenticateByTrsustedPrincipal", targetNamespace = "http://impl.service.wfe.runa.ru/", className = "ru.runa.wfe.webservice.AuthenticateByTrsustedPrincipal")
    @ResponseWrapper(localName = "authenticateByTrsustedPrincipalResponse", targetNamespace = "http://impl.service.wfe.runa.ru/", className = "ru.runa.wfe.webservice.AuthenticateByTrsustedPrincipalResponse")
    public User authenticateByTrsustedPrincipal(
        @WebParam(name = "serviceUser", targetNamespace = "")
        User serviceUser,
        @WebParam(name = "login", targetNamespace = "")
        String login);

    /**
     * 
     * @return
     *     returns ru.runa.wfe.webservice.User
     */
    @WebMethod
    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "authenticateByCallerPrincipal", targetNamespace = "http://impl.service.wfe.runa.ru/", className = "ru.runa.wfe.webservice.AuthenticateByCallerPrincipal")
    @ResponseWrapper(localName = "authenticateByCallerPrincipalResponse", targetNamespace = "http://impl.service.wfe.runa.ru/", className = "ru.runa.wfe.webservice.AuthenticateByCallerPrincipalResponse")
    public User authenticateByCallerPrincipal();

}
