
package ru.runa.wfe.webservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2-12/14/2009 02:16 PM(ramkris)-
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "DefinitionWebService", targetNamespace = "http://impl.service.wfe.runa.ru/", wsdlLocation = "http://localhost:8080/wfe-service-4.3.0-SNAPSHOT/DefinitionWebService/DefinitionAPI?wsdl")
public class DefinitionWebService
    extends Service
{

    private final static URL DEFINITIONWEBSERVICE_WSDL_LOCATION;
    private final static WebServiceException DEFINITIONWEBSERVICE_EXCEPTION;
    private final static QName DEFINITIONWEBSERVICE_QNAME = new QName("http://impl.service.wfe.runa.ru/", "DefinitionWebService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/wfe-service-4.3.0-SNAPSHOT/DefinitionWebService/DefinitionAPI?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        DEFINITIONWEBSERVICE_WSDL_LOCATION = url;
        DEFINITIONWEBSERVICE_EXCEPTION = e;
    }

    public DefinitionWebService() {
        super(__getWsdlLocation(), DEFINITIONWEBSERVICE_QNAME);
    }

    public DefinitionWebService(WebServiceFeature... features) {
        super(__getWsdlLocation(), DEFINITIONWEBSERVICE_QNAME, features);
    }

    public DefinitionWebService(URL wsdlLocation) {
        super(wsdlLocation, DEFINITIONWEBSERVICE_QNAME);
    }

    public DefinitionWebService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, DEFINITIONWEBSERVICE_QNAME, features);
    }

    public DefinitionWebService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DefinitionWebService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns DefinitionAPI
     */
    @WebEndpoint(name = "DefinitionAPIPort")
    public DefinitionAPI getDefinitionAPIPort() {
        return super.getPort(new QName("http://impl.service.wfe.runa.ru/", "DefinitionAPIPort"), DefinitionAPI.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DefinitionAPI
     */
    @WebEndpoint(name = "DefinitionAPIPort")
    public DefinitionAPI getDefinitionAPIPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://impl.service.wfe.runa.ru/", "DefinitionAPIPort"), DefinitionAPI.class, features);
    }

    private static URL __getWsdlLocation() {
        if (DEFINITIONWEBSERVICE_EXCEPTION!= null) {
            throw DEFINITIONWEBSERVICE_EXCEPTION;
        }
        return DEFINITIONWEBSERVICE_WSDL_LOCATION;
    }

}
