
package ru.runa.wfe.webservice;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2-12/14/2009 02:16 PM(ramkris)-
 * Generated source version: 2.2
 * 
 */
@WebService(name = "DefinitionAPI", targetNamespace = "http://impl.service.wfe.runa.ru/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface DefinitionAPI {


    /**
     * 
     * @param user
     * @param definitionId
     * @return
     *     returns java.util.List<ru.runa.wfe.webservice.Variable>
     */
    @WebMethod
    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "getVariableDefinitionsWS", targetNamespace = "http://impl.service.wfe.runa.ru/", className = "ru.runa.wfe.webservice.GetVariableDefinitionsWS")
    @ResponseWrapper(localName = "getVariableDefinitionsWSResponse", targetNamespace = "http://impl.service.wfe.runa.ru/", className = "ru.runa.wfe.webservice.GetVariableDefinitionsWSResponse")
    public List<Variable> getVariableDefinitionsWS(
        @WebParam(name = "user", targetNamespace = "")
        User user,
        @WebParam(name = "definitionId", targetNamespace = "")
        Long definitionId);

    /**
     * 
     * @param par
     * @param processId
     * @param categories
     * @param user
     * @return
     *     returns ru.runa.wfe.webservice.WfDefinition
     */
    @WebMethod
    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "redeployProcessDefinition", targetNamespace = "http://impl.service.wfe.runa.ru/", className = "ru.runa.wfe.webservice.RedeployProcessDefinition")
    @ResponseWrapper(localName = "redeployProcessDefinitionResponse", targetNamespace = "http://impl.service.wfe.runa.ru/", className = "ru.runa.wfe.webservice.RedeployProcessDefinitionResponse")
    public WfDefinition redeployProcessDefinition(
        @WebParam(name = "user", targetNamespace = "")
        User user,
        @WebParam(name = "processId", targetNamespace = "")
        Long processId,
        @WebParam(name = "par", targetNamespace = "")
        byte[] par,
        @WebParam(name = "categories", targetNamespace = "")
        List<String> categories);

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns ru.runa.wfe.webservice.Interaction
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getTaskNodeInteraction", targetNamespace = "http://impl.service.wfe.runa.ru/", className = "ru.runa.wfe.webservice.GetTaskNodeInteraction")
    @ResponseWrapper(localName = "getTaskNodeInteractionResponse", targetNamespace = "http://impl.service.wfe.runa.ru/", className = "ru.runa.wfe.webservice.GetTaskNodeInteractionResponse")
    public Interaction getTaskNodeInteraction(
        @WebParam(name = "arg0", targetNamespace = "")
        User arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        Long arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2);

    /**
     * 
     * @param name
     * @param user
     * @param definitionId
     * @return
     *     returns ru.runa.wfe.webservice.UserType
     */
    @WebMethod
    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "getUserType", targetNamespace = "http://impl.service.wfe.runa.ru/", className = "ru.runa.wfe.webservice.GetUserType")
    @ResponseWrapper(localName = "getUserTypeResponse", targetNamespace = "http://impl.service.wfe.runa.ru/", className = "ru.runa.wfe.webservice.GetUserTypeResponse")
    public UserType getUserType(
        @WebParam(name = "user", targetNamespace = "")
        User user,
        @WebParam(name = "definitionId", targetNamespace = "")
        Long definitionId,
        @WebParam(name = "name", targetNamespace = "")
        String name);

    /**
     * 
     * @param processId
     * @param processArchive
     * @param user
     * @return
     *     returns ru.runa.wfe.webservice.WfDefinition
     */
    @WebMethod
    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "updateProcessDefinition", targetNamespace = "http://impl.service.wfe.runa.ru/", className = "ru.runa.wfe.webservice.UpdateProcessDefinition")
    @ResponseWrapper(localName = "updateProcessDefinitionResponse", targetNamespace = "http://impl.service.wfe.runa.ru/", className = "ru.runa.wfe.webservice.UpdateProcessDefinitionResponse")
    public WfDefinition updateProcessDefinition(
        @WebParam(name = "user", targetNamespace = "")
        User user,
        @WebParam(name = "processId", targetNamespace = "")
        Long processId,
        @WebParam(name = "processArchive", targetNamespace = "")
        byte[] processArchive);

    /**
     * 
     * @param taskId
     * @param user
     * @return
     *     returns ru.runa.wfe.webservice.Interaction
     */
    @WebMethod
    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "getTaskInteraction", targetNamespace = "http://impl.service.wfe.runa.ru/", className = "ru.runa.wfe.webservice.GetTaskInteraction")
    @ResponseWrapper(localName = "getTaskInteractionResponse", targetNamespace = "http://impl.service.wfe.runa.ru/", className = "ru.runa.wfe.webservice.GetTaskInteractionResponse")
    public Interaction getTaskInteraction(
        @WebParam(name = "user", targetNamespace = "")
        User user,
        @WebParam(name = "taskId", targetNamespace = "")
        Long taskId);

    /**
     * 
     * @param variableName
     * @param user
     * @param definitionId
     * @return
     *     returns ru.runa.wfe.webservice.Variable
     */
    @WebMethod
    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "getVariableDefinitionWS", targetNamespace = "http://impl.service.wfe.runa.ru/", className = "ru.runa.wfe.webservice.GetVariableDefinitionWS")
    @ResponseWrapper(localName = "getVariableDefinitionWSResponse", targetNamespace = "http://impl.service.wfe.runa.ru/", className = "ru.runa.wfe.webservice.GetVariableDefinitionWSResponse")
    public Variable getVariableDefinitionWS(
        @WebParam(name = "user", targetNamespace = "")
        User user,
        @WebParam(name = "definitionId", targetNamespace = "")
        Long definitionId,
        @WebParam(name = "variableName", targetNamespace = "")
        String variableName);

    /**
     * 
     * @param user
     * @param definitionId
     * @return
     *     returns java.util.List<ru.runa.wfe.webservice.SwimlaneDefinition>
     */
    @WebMethod
    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "getSwimlaneDefinitions", targetNamespace = "http://impl.service.wfe.runa.ru/", className = "ru.runa.wfe.webservice.GetSwimlaneDefinitions")
    @ResponseWrapper(localName = "getSwimlaneDefinitionsResponse", targetNamespace = "http://impl.service.wfe.runa.ru/", className = "ru.runa.wfe.webservice.GetSwimlaneDefinitionsResponse")
    public List<SwimlaneDefinition> getSwimlaneDefinitions(
        @WebParam(name = "user", targetNamespace = "")
        User user,
        @WebParam(name = "definitionId", targetNamespace = "")
        Long definitionId);

    /**
     * 
     * @param user
     * @param subprocessId
     * @param definitionId
     * @return
     *     returns byte[]
     */
    @WebMethod
    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "getProcessDefinitionGraph", targetNamespace = "http://impl.service.wfe.runa.ru/", className = "ru.runa.wfe.webservice.GetProcessDefinitionGraph")
    @ResponseWrapper(localName = "getProcessDefinitionGraphResponse", targetNamespace = "http://impl.service.wfe.runa.ru/", className = "ru.runa.wfe.webservice.GetProcessDefinitionGraphResponse")
    public byte[] getProcessDefinitionGraph(
        @WebParam(name = "user", targetNamespace = "")
        User user,
        @WebParam(name = "definitionId", targetNamespace = "")
        Long definitionId,
        @WebParam(name = "subprocessId", targetNamespace = "")
        String subprocessId);

    /**
     * 
     * @param user
     * @param definitionId
     * @return
     *     returns ru.runa.wfe.webservice.Interaction
     */
    @WebMethod
    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "getStartInteraction", targetNamespace = "http://impl.service.wfe.runa.ru/", className = "ru.runa.wfe.webservice.GetStartInteraction")
    @ResponseWrapper(localName = "getStartInteractionResponse", targetNamespace = "http://impl.service.wfe.runa.ru/", className = "ru.runa.wfe.webservice.GetStartInteractionResponse")
    public Interaction getStartInteraction(
        @WebParam(name = "user", targetNamespace = "")
        User user,
        @WebParam(name = "definitionId", targetNamespace = "")
        Long definitionId);

    /**
     * 
     * @param par
     * @param categories
     * @param user
     * @return
     *     returns ru.runa.wfe.webservice.WfDefinition
     */
    @WebMethod
    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "deployProcessDefinition", targetNamespace = "http://impl.service.wfe.runa.ru/", className = "ru.runa.wfe.webservice.DeployProcessDefinition")
    @ResponseWrapper(localName = "deployProcessDefinitionResponse", targetNamespace = "http://impl.service.wfe.runa.ru/", className = "ru.runa.wfe.webservice.DeployProcessDefinitionResponse")
    public WfDefinition deployProcessDefinition(
        @WebParam(name = "user", targetNamespace = "")
        User user,
        @WebParam(name = "par", targetNamespace = "")
        byte[] par,
        @WebParam(name = "categories", targetNamespace = "")
        List<String> categories);

    /**
     * 
     * @param user
     * @param subprocessId
     * @param definitionId
     * @return
     *     returns java.util.List<ru.runa.wfe.webservice.GraphElementPresentation>
     */
    @WebMethod
    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "getProcessDefinitionGraphElements", targetNamespace = "http://impl.service.wfe.runa.ru/", className = "ru.runa.wfe.webservice.GetProcessDefinitionGraphElements")
    @ResponseWrapper(localName = "getProcessDefinitionGraphElementsResponse", targetNamespace = "http://impl.service.wfe.runa.ru/", className = "ru.runa.wfe.webservice.GetProcessDefinitionGraphElementsResponse")
    public List<GraphElementPresentation> getProcessDefinitionGraphElements(
        @WebParam(name = "user", targetNamespace = "")
        User user,
        @WebParam(name = "definitionId", targetNamespace = "")
        Long definitionId,
        @WebParam(name = "subprocessId", targetNamespace = "")
        String subprocessId);

    /**
     * 
     * @param name
     * @param user
     * @return
     *     returns java.util.List<ru.runa.wfe.webservice.WfDefinition>
     */
    @WebMethod
    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "getProcessDefinitionHistory", targetNamespace = "http://impl.service.wfe.runa.ru/", className = "ru.runa.wfe.webservice.GetProcessDefinitionHistory")
    @ResponseWrapper(localName = "getProcessDefinitionHistoryResponse", targetNamespace = "http://impl.service.wfe.runa.ru/", className = "ru.runa.wfe.webservice.GetProcessDefinitionHistoryResponse")
    public List<WfDefinition> getProcessDefinitionHistory(
        @WebParam(name = "user", targetNamespace = "")
        User user,
        @WebParam(name = "name", targetNamespace = "")
        String name);

    /**
     * 
     * @param user
     * @param definitionId
     * @return
     *     returns java.util.List<ru.runa.wfe.webservice.UserType>
     */
    @WebMethod
    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "getUserTypes", targetNamespace = "http://impl.service.wfe.runa.ru/", className = "ru.runa.wfe.webservice.GetUserTypes")
    @ResponseWrapper(localName = "getUserTypesResponse", targetNamespace = "http://impl.service.wfe.runa.ru/", className = "ru.runa.wfe.webservice.GetUserTypesResponse")
    public List<UserType> getUserTypes(
        @WebParam(name = "user", targetNamespace = "")
        User user,
        @WebParam(name = "definitionId", targetNamespace = "")
        Long definitionId);

    /**
     * 
     * @param user
     * @param definitionId
     * @return
     *     returns ru.runa.wfe.webservice.ProcessDefinition
     * @throws DefinitionDoesNotExistException_Exception
     */
    @WebMethod
    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "getParsedProcessDefinition", targetNamespace = "http://impl.service.wfe.runa.ru/", className = "ru.runa.wfe.webservice.GetParsedProcessDefinition")
    @ResponseWrapper(localName = "getParsedProcessDefinitionResponse", targetNamespace = "http://impl.service.wfe.runa.ru/", className = "ru.runa.wfe.webservice.GetParsedProcessDefinitionResponse")
    public ProcessDefinition getParsedProcessDefinition(
        @WebParam(name = "user", targetNamespace = "")
        User user,
        @WebParam(name = "definitionId", targetNamespace = "")
        Long definitionId)
        throws DefinitionDoesNotExistException_Exception
    ;

    /**
     * 
     * @param taskId
     * @param withTimerTransitions
     * @param user
     * @param definitionId
     * @return
     *     returns java.util.List<java.lang.String>
     */
    @WebMethod
    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "getOutputTransitionNames", targetNamespace = "http://impl.service.wfe.runa.ru/", className = "ru.runa.wfe.webservice.GetOutputTransitionNames")
    @ResponseWrapper(localName = "getOutputTransitionNamesResponse", targetNamespace = "http://impl.service.wfe.runa.ru/", className = "ru.runa.wfe.webservice.GetOutputTransitionNamesResponse")
    public List<String> getOutputTransitionNames(
        @WebParam(name = "user", targetNamespace = "")
        User user,
        @WebParam(name = "definitionId", targetNamespace = "")
        Long definitionId,
        @WebParam(name = "taskId", targetNamespace = "")
        Long taskId,
        @WebParam(name = "withTimerTransitions", targetNamespace = "")
        boolean withTimerTransitions);

    /**
     * 
     * @param user
     * @param definitionId
     * @return
     *     returns ru.runa.wfe.webservice.WfDefinition
     */
    @WebMethod
    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "getProcessDefinition", targetNamespace = "http://impl.service.wfe.runa.ru/", className = "ru.runa.wfe.webservice.GetProcessDefinition")
    @ResponseWrapper(localName = "getProcessDefinitionResponse", targetNamespace = "http://impl.service.wfe.runa.ru/", className = "ru.runa.wfe.webservice.GetProcessDefinitionResponse")
    public WfDefinition getProcessDefinition(
        @WebParam(name = "user", targetNamespace = "")
        User user,
        @WebParam(name = "definitionId", targetNamespace = "")
        Long definitionId);

    /**
     * 
     * @param fileName
     * @param user
     * @param definitionId
     * @return
     *     returns byte[]
     */
    @WebMethod
    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "getProcessDefinitionFile", targetNamespace = "http://impl.service.wfe.runa.ru/", className = "ru.runa.wfe.webservice.GetProcessDefinitionFile")
    @ResponseWrapper(localName = "getProcessDefinitionFileResponse", targetNamespace = "http://impl.service.wfe.runa.ru/", className = "ru.runa.wfe.webservice.GetProcessDefinitionFileResponse")
    public byte[] getProcessDefinitionFile(
        @WebParam(name = "user", targetNamespace = "")
        User user,
        @WebParam(name = "definitionId", targetNamespace = "")
        Long definitionId,
        @WebParam(name = "fileName", targetNamespace = "")
        String fileName);

    /**
     * 
     * @param enablePaging
     * @param batchPresentation
     * @param user
     * @return
     *     returns java.util.List<ru.runa.wfe.webservice.WfDefinition>
     */
    @WebMethod
    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "getProcessDefinitions", targetNamespace = "http://impl.service.wfe.runa.ru/", className = "ru.runa.wfe.webservice.GetProcessDefinitions")
    @ResponseWrapper(localName = "getProcessDefinitionsResponse", targetNamespace = "http://impl.service.wfe.runa.ru/", className = "ru.runa.wfe.webservice.GetProcessDefinitionsResponse")
    public List<WfDefinition> getProcessDefinitions(
        @WebParam(name = "user", targetNamespace = "")
        User user,
        @WebParam(name = "batchPresentation", targetNamespace = "")
        BatchPresentation batchPresentation,
        @WebParam(name = "enablePaging", targetNamespace = "")
        boolean enablePaging);

    /**
     * 
     * @param definitionName
     * @param user
     * @param version
     */
    @WebMethod
    @RequestWrapper(localName = "undeployProcessDefinition", targetNamespace = "http://impl.service.wfe.runa.ru/", className = "ru.runa.wfe.webservice.UndeployProcessDefinition")
    @ResponseWrapper(localName = "undeployProcessDefinitionResponse", targetNamespace = "http://impl.service.wfe.runa.ru/", className = "ru.runa.wfe.webservice.UndeployProcessDefinitionResponse")
    public void undeployProcessDefinition(
        @WebParam(name = "user", targetNamespace = "")
        User user,
        @WebParam(name = "definitionName", targetNamespace = "")
        String definitionName,
        @WebParam(name = "version", targetNamespace = "")
        Long version);

    /**
     * 
     * @param batchPresentation
     * @param user
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "getProcessDefinitionsCount", targetNamespace = "http://impl.service.wfe.runa.ru/", className = "ru.runa.wfe.webservice.GetProcessDefinitionsCount")
    @ResponseWrapper(localName = "getProcessDefinitionsCountResponse", targetNamespace = "http://impl.service.wfe.runa.ru/", className = "ru.runa.wfe.webservice.GetProcessDefinitionsCountResponse")
    public int getProcessDefinitionsCount(
        @WebParam(name = "user", targetNamespace = "")
        User user,
        @WebParam(name = "batchPresentation", targetNamespace = "")
        BatchPresentation batchPresentation);

    /**
     * 
     * @param definitionName
     * @param user
     * @return
     *     returns ru.runa.wfe.webservice.WfDefinition
     */
    @WebMethod
    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "getLatestProcessDefinition", targetNamespace = "http://impl.service.wfe.runa.ru/", className = "ru.runa.wfe.webservice.GetLatestProcessDefinition")
    @ResponseWrapper(localName = "getLatestProcessDefinitionResponse", targetNamespace = "http://impl.service.wfe.runa.ru/", className = "ru.runa.wfe.webservice.GetLatestProcessDefinitionResponse")
    public WfDefinition getLatestProcessDefinition(
        @WebParam(name = "user", targetNamespace = "")
        User user,
        @WebParam(name = "definitionName", targetNamespace = "")
        String definitionName);

}
