
package ru.runa.wfe.webservice;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2-12/14/2009 02:16 PM(ramkris)-
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "DefinitionDoesNotExistException", targetNamespace = "http://impl.service.wfe.runa.ru/")
public class DefinitionDoesNotExistException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private DefinitionDoesNotExistException faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public DefinitionDoesNotExistException_Exception(String message, DefinitionDoesNotExistException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public DefinitionDoesNotExistException_Exception(String message, DefinitionDoesNotExistException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: ru.runa.wfe.webservice.DefinitionDoesNotExistException
     */
    public DefinitionDoesNotExistException getFaultInfo() {
        return faultInfo;
    }

}
