
package ru.runa.wfe.webservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2-12/14/2009 02:16 PM(ramkris)-
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ExecutionWebService", targetNamespace = "http://impl.service.wfe.runa.ru/", wsdlLocation = "http://localhost:8080/wfe-service-4.3.0-SNAPSHOT/ExecutionWebService/ExecutionAPI?wsdl")
public class ExecutionWebService
    extends Service
{

    private final static URL EXECUTIONWEBSERVICE_WSDL_LOCATION;
    private final static WebServiceException EXECUTIONWEBSERVICE_EXCEPTION;
    private final static QName EXECUTIONWEBSERVICE_QNAME = new QName("http://impl.service.wfe.runa.ru/", "ExecutionWebService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/wfe-service-4.3.0-SNAPSHOT/ExecutionWebService/ExecutionAPI?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        EXECUTIONWEBSERVICE_WSDL_LOCATION = url;
        EXECUTIONWEBSERVICE_EXCEPTION = e;
    }

    public ExecutionWebService() {
        super(__getWsdlLocation(), EXECUTIONWEBSERVICE_QNAME);
    }

    public ExecutionWebService(WebServiceFeature... features) {
        super(__getWsdlLocation(), EXECUTIONWEBSERVICE_QNAME, features);
    }

    public ExecutionWebService(URL wsdlLocation) {
        super(wsdlLocation, EXECUTIONWEBSERVICE_QNAME);
    }

    public ExecutionWebService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, EXECUTIONWEBSERVICE_QNAME, features);
    }

    public ExecutionWebService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ExecutionWebService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ExecutionAPI
     */
    @WebEndpoint(name = "ExecutionAPIPort")
    public ExecutionAPI getExecutionAPIPort() {
        return super.getPort(new QName("http://impl.service.wfe.runa.ru/", "ExecutionAPIPort"), ExecutionAPI.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ExecutionAPI
     */
    @WebEndpoint(name = "ExecutionAPIPort")
    public ExecutionAPI getExecutionAPIPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://impl.service.wfe.runa.ru/", "ExecutionAPIPort"), ExecutionAPI.class, features);
    }

    private static URL __getWsdlLocation() {
        if (EXECUTIONWEBSERVICE_EXCEPTION!= null) {
            throw EXECUTIONWEBSERVICE_EXCEPTION;
        }
        return EXECUTIONWEBSERVICE_WSDL_LOCATION;
    }

}
