
package ru.runa.wfe.webservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2-12/14/2009 02:16 PM(ramkris)-
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ExecutorWebService", targetNamespace = "http://impl.service.wfe.runa.ru/", wsdlLocation = "http://localhost:8080/wfe-service-4.3.0-SNAPSHOT/ExecutorWebService/ExecutorAPI?wsdl")
public class ExecutorWebService
    extends Service
{

    private final static URL EXECUTORWEBSERVICE_WSDL_LOCATION;
    private final static WebServiceException EXECUTORWEBSERVICE_EXCEPTION;
    private final static QName EXECUTORWEBSERVICE_QNAME = new QName("http://impl.service.wfe.runa.ru/", "ExecutorWebService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/wfe-service-4.3.0-SNAPSHOT/ExecutorWebService/ExecutorAPI?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        EXECUTORWEBSERVICE_WSDL_LOCATION = url;
        EXECUTORWEBSERVICE_EXCEPTION = e;
    }

    public ExecutorWebService() {
        super(__getWsdlLocation(), EXECUTORWEBSERVICE_QNAME);
    }

    public ExecutorWebService(WebServiceFeature... features) {
        super(__getWsdlLocation(), EXECUTORWEBSERVICE_QNAME, features);
    }

    public ExecutorWebService(URL wsdlLocation) {
        super(wsdlLocation, EXECUTORWEBSERVICE_QNAME);
    }

    public ExecutorWebService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, EXECUTORWEBSERVICE_QNAME, features);
    }

    public ExecutorWebService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ExecutorWebService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ExecutorAPI
     */
    @WebEndpoint(name = "ExecutorAPIPort")
    public ExecutorAPI getExecutorAPIPort() {
        return super.getPort(new QName("http://impl.service.wfe.runa.ru/", "ExecutorAPIPort"), ExecutorAPI.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ExecutorAPI
     */
    @WebEndpoint(name = "ExecutorAPIPort")
    public ExecutorAPI getExecutorAPIPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://impl.service.wfe.runa.ru/", "ExecutorAPIPort"), ExecutorAPI.class, features);
    }

    private static URL __getWsdlLocation() {
        if (EXECUTORWEBSERVICE_EXCEPTION!= null) {
            throw EXECUTORWEBSERVICE_EXCEPTION;
        }
        return EXECUTORWEBSERVICE_WSDL_LOCATION;
    }

}
