
package ru.runa.wfe.webservice;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2-12/14/2009 02:16 PM(ramkris)-
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ExecutionAPI", targetNamespace = "http://impl.service.wfe.runa.ru/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ExecutionAPI {


    /**
     * 
     * @param user
     * @param filter
     * @return
     *     returns java.util.List<ru.runa.wfe.webservice.WfProcess>
     */
    @WebMethod
    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "getProcessesByFilter", targetNamespace = "http://impl.service.wfe.runa.ru/", className = "ru.runa.wfe.webservice.GetProcessesByFilter")
    @ResponseWrapper(localName = "getProcessesByFilterResponse", targetNamespace = "http://impl.service.wfe.runa.ru/", className = "ru.runa.wfe.webservice.GetProcessesByFilterResponse")
    public List<WfProcess> getProcessesByFilter(
        @WebParam(name = "user", targetNamespace = "")
        User user,
        @WebParam(name = "filter", targetNamespace = "")
        ProcessFilter filter);

    /**
     * 
     * @param user
     * @param filter
     */
    @WebMethod
    @RequestWrapper(localName = "removeProcesses", targetNamespace = "http://impl.service.wfe.runa.ru/", className = "ru.runa.wfe.webservice.RemoveProcesses")
    @ResponseWrapper(localName = "removeProcessesResponse", targetNamespace = "http://impl.service.wfe.runa.ru/", className = "ru.runa.wfe.webservice.RemoveProcessesResponse")
    public void removeProcesses(
        @WebParam(name = "user", targetNamespace = "")
        User user,
        @WebParam(name = "filter", targetNamespace = "")
        ProcessFilter filter);

    /**
     * 
     * @param variableName
     * @param processId
     * @param user
     * @return
     *     returns ru.runa.wfe.webservice.Variable
     */
    @WebMethod
    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "getVariableWS", targetNamespace = "http://impl.service.wfe.runa.ru/", className = "ru.runa.wfe.webservice.GetVariableWS")
    @ResponseWrapper(localName = "getVariableWSResponse", targetNamespace = "http://impl.service.wfe.runa.ru/", className = "ru.runa.wfe.webservice.GetVariableWSResponse")
    public Variable getVariableWS(
        @WebParam(name = "user", targetNamespace = "")
        User user,
        @WebParam(name = "processId", targetNamespace = "")
        Long processId,
        @WebParam(name = "variableName", targetNamespace = "")
        String variableName);

    /**
     * 
     * @param processId
     * @param user
     * @param version
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "upgradeProcessToDefinitionVersion", targetNamespace = "http://impl.service.wfe.runa.ru/", className = "ru.runa.wfe.webservice.UpgradeProcessToDefinitionVersion")
    @ResponseWrapper(localName = "upgradeProcessToDefinitionVersionResponse", targetNamespace = "http://impl.service.wfe.runa.ru/", className = "ru.runa.wfe.webservice.UpgradeProcessToDefinitionVersionResponse")
    public boolean upgradeProcessToDefinitionVersion(
        @WebParam(name = "user", targetNamespace = "")
        User user,
        @WebParam(name = "processId", targetNamespace = "")
        Long processId,
        @WebParam(name = "version", targetNamespace = "")
        Long version);

    /**
     * 
     * @param swimlaneName
     * @param processId
     * @param executor
     * @param user
     */
    @WebMethod
    @RequestWrapper(localName = "assignSwimlane", targetNamespace = "http://impl.service.wfe.runa.ru/", className = "ru.runa.wfe.webservice.AssignSwimlane")
    @ResponseWrapper(localName = "assignSwimlaneResponse", targetNamespace = "http://impl.service.wfe.runa.ru/", className = "ru.runa.wfe.webservice.AssignSwimlaneResponse")
    public void assignSwimlane(
        @WebParam(name = "user", targetNamespace = "")
        User user,
        @WebParam(name = "processId", targetNamespace = "")
        Long processId,
        @WebParam(name = "swimlaneName", targetNamespace = "")
        String swimlaneName,
        @WebParam(name = "executor", targetNamespace = "")
        WfExecutor executor);

    /**
     * 
     * @param variableName
     * @param processId
     * @param user
     * @return
     *     returns ru.runa.wfe.webservice.WfVariableStub
     */
    @WebMethod
    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "getVariable", targetNamespace = "http://impl.service.wfe.runa.ru/", className = "ru.runa.wfe.webservice.GetVariable")
    @ResponseWrapper(localName = "getVariableResponse", targetNamespace = "http://impl.service.wfe.runa.ru/", className = "ru.runa.wfe.webservice.GetVariableResponse")
    public WfVariableStub getVariable(
        @WebParam(name = "user", targetNamespace = "")
        User user,
        @WebParam(name = "processId", targetNamespace = "")
        Long processId,
        @WebParam(name = "variableName", targetNamespace = "")
        String variableName);

    /**
     * 
     * @param batchPresentation
     * @param user
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "getProcessesCount", targetNamespace = "http://impl.service.wfe.runa.ru/", className = "ru.runa.wfe.webservice.GetProcessesCount")
    @ResponseWrapper(localName = "getProcessesCountResponse", targetNamespace = "http://impl.service.wfe.runa.ru/", className = "ru.runa.wfe.webservice.GetProcessesCountResponse")
    public int getProcessesCount(
        @WebParam(name = "user", targetNamespace = "")
        User user,
        @WebParam(name = "batchPresentation", targetNamespace = "")
        BatchPresentation batchPresentation);

    /**
     * 
     * @param batchPresentation
     * @param user
     * @return
     *     returns java.util.List<ru.runa.wfe.webservice.WfProcess>
     */
    @WebMethod
    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "getProcesses", targetNamespace = "http://impl.service.wfe.runa.ru/", className = "ru.runa.wfe.webservice.GetProcesses")
    @ResponseWrapper(localName = "getProcessesResponse", targetNamespace = "http://impl.service.wfe.runa.ru/", className = "ru.runa.wfe.webservice.GetProcessesResponse")
    public List<WfProcess> getProcesses(
        @WebParam(name = "user", targetNamespace = "")
        User user,
        @WebParam(name = "batchPresentation", targetNamespace = "")
        BatchPresentation batchPresentation);

    /**
     * 
     * @param processId
     * @param user
     * @return
     *     returns java.util.List<ru.runa.wfe.webservice.Variable>
     */
    @WebMethod
    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "getVariablesWS", targetNamespace = "http://impl.service.wfe.runa.ru/", className = "ru.runa.wfe.webservice.GetVariablesWS")
    @ResponseWrapper(localName = "getVariablesWSResponse", targetNamespace = "http://impl.service.wfe.runa.ru/", className = "ru.runa.wfe.webservice.GetVariablesWSResponse")
    public List<Variable> getVariablesWS(
        @WebParam(name = "user", targetNamespace = "")
        User user,
        @WebParam(name = "processId", targetNamespace = "")
        Long processId);

    /**
     * 
     * @param id
     * @param user
     * @return
     *     returns ru.runa.wfe.webservice.WfProcess
     */
    @WebMethod
    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "getParentProcess", targetNamespace = "http://impl.service.wfe.runa.ru/", className = "ru.runa.wfe.webservice.GetParentProcess")
    @ResponseWrapper(localName = "getParentProcessResponse", targetNamespace = "http://impl.service.wfe.runa.ru/", className = "ru.runa.wfe.webservice.GetParentProcessResponse")
    public WfProcess getParentProcess(
        @WebParam(name = "user", targetNamespace = "")
        User user,
        @WebParam(name = "id", targetNamespace = "")
        Long id);

    /**
     * 
     * @param id
     * @param user
     * @return
     *     returns ru.runa.wfe.webservice.WfProcess
     */
    @WebMethod
    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "getProcess", targetNamespace = "http://impl.service.wfe.runa.ru/", className = "ru.runa.wfe.webservice.GetProcess")
    @ResponseWrapper(localName = "getProcessResponse", targetNamespace = "http://impl.service.wfe.runa.ru/", className = "ru.runa.wfe.webservice.GetProcessResponse")
    public WfProcess getProcess(
        @WebParam(name = "user", targetNamespace = "")
        User user,
        @WebParam(name = "id", targetNamespace = "")
        Long id);

    /**
     * 
     * @param processId
     * @param user
     * @param variables
     */
    @WebMethod
    @RequestWrapper(localName = "updateVariablesWS", targetNamespace = "http://impl.service.wfe.runa.ru/", className = "ru.runa.wfe.webservice.UpdateVariablesWS")
    @ResponseWrapper(localName = "updateVariablesWSResponse", targetNamespace = "http://impl.service.wfe.runa.ru/", className = "ru.runa.wfe.webservice.UpdateVariablesWSResponse")
    public void updateVariablesWS(
        @WebParam(name = "user", targetNamespace = "")
        User user,
        @WebParam(name = "processId", targetNamespace = "")
        Long processId,
        @WebParam(name = "variables", targetNamespace = "")
        List<Variable> variables);

    /**
     * 
     * @param variableName
     * @param processId
     * @param user
     * @return
     *     returns ru.runa.wfe.webservice.FileVariable
     */
    @WebMethod
    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "getFileVariableValue", targetNamespace = "http://impl.service.wfe.runa.ru/", className = "ru.runa.wfe.webservice.GetFileVariableValue")
    @ResponseWrapper(localName = "getFileVariableValueResponse", targetNamespace = "http://impl.service.wfe.runa.ru/", className = "ru.runa.wfe.webservice.GetFileVariableValueResponse")
    public FileVariable getFileVariableValue(
        @WebParam(name = "user", targetNamespace = "")
        User user,
        @WebParam(name = "processId", targetNamespace = "")
        Long processId,
        @WebParam(name = "variableName", targetNamespace = "")
        String variableName);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.util.List<ru.runa.wfe.webservice.ProcessError>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getProcessErrors", targetNamespace = "http://impl.service.wfe.runa.ru/", className = "ru.runa.wfe.webservice.GetProcessErrors")
    @ResponseWrapper(localName = "getProcessErrorsResponse", targetNamespace = "http://impl.service.wfe.runa.ru/", className = "ru.runa.wfe.webservice.GetProcessErrorsResponse")
    public List<ProcessError> getProcessErrors(
        @WebParam(name = "arg0", targetNamespace = "")
        User arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        Long arg1);

    /**
     * 
     * @param definitionName
     * @param user
     * @param variables
     * @return
     *     returns java.lang.Long
     */
    @WebMethod
    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "startProcessWS", targetNamespace = "http://impl.service.wfe.runa.ru/", className = "ru.runa.wfe.webservice.StartProcessWS")
    @ResponseWrapper(localName = "startProcessWSResponse", targetNamespace = "http://impl.service.wfe.runa.ru/", className = "ru.runa.wfe.webservice.StartProcessWSResponse")
    public Long startProcessWS(
        @WebParam(name = "user", targetNamespace = "")
        User user,
        @WebParam(name = "definitionName", targetNamespace = "")
        String definitionName,
        @WebParam(name = "variables", targetNamespace = "")
        List<Variable> variables);

    /**
     * 
     * @param processId
     * @param user
     * @param subprocessId
     * @return
     *     returns java.util.List<ru.runa.wfe.webservice.GraphElementPresentation>
     */
    @WebMethod
    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "getProcessDiagramElements", targetNamespace = "http://impl.service.wfe.runa.ru/", className = "ru.runa.wfe.webservice.GetProcessDiagramElements")
    @ResponseWrapper(localName = "getProcessDiagramElementsResponse", targetNamespace = "http://impl.service.wfe.runa.ru/", className = "ru.runa.wfe.webservice.GetProcessDiagramElementsResponse")
    public List<GraphElementPresentation> getProcessDiagramElements(
        @WebParam(name = "user", targetNamespace = "")
        User user,
        @WebParam(name = "processId", targetNamespace = "")
        Long processId,
        @WebParam(name = "subprocessId", targetNamespace = "")
        String subprocessId);

    /**
     * 
     * @param taskId
     * @param variableName
     * @param processId
     * @param user
     * @return
     *     returns ru.runa.wfe.webservice.WfVariableStub
     */
    @WebMethod
    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "getTaskVariable", targetNamespace = "http://impl.service.wfe.runa.ru/", className = "ru.runa.wfe.webservice.GetTaskVariable")
    @ResponseWrapper(localName = "getTaskVariableResponse", targetNamespace = "http://impl.service.wfe.runa.ru/", className = "ru.runa.wfe.webservice.GetTaskVariableResponse")
    public WfVariableStub getTaskVariable(
        @WebParam(name = "user", targetNamespace = "")
        User user,
        @WebParam(name = "processId", targetNamespace = "")
        Long processId,
        @WebParam(name = "taskId", targetNamespace = "")
        Long taskId,
        @WebParam(name = "variableName", targetNamespace = "")
        String variableName);

    /**
     * 
     * @param processId
     * @param recursive
     * @param user
     * @return
     *     returns java.util.List<ru.runa.wfe.webservice.WfJob>
     */
    @WebMethod
    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "getProcessJobs", targetNamespace = "http://impl.service.wfe.runa.ru/", className = "ru.runa.wfe.webservice.GetProcessJobs")
    @ResponseWrapper(localName = "getProcessJobsResponse", targetNamespace = "http://impl.service.wfe.runa.ru/", className = "ru.runa.wfe.webservice.GetProcessJobsResponse")
    public List<WfJob> getProcessJobs(
        @WebParam(name = "user", targetNamespace = "")
        User user,
        @WebParam(name = "processId", targetNamespace = "")
        Long processId,
        @WebParam(name = "recursive", targetNamespace = "")
        boolean recursive);

    /**
     * 
     * @param id
     * @param recursive
     * @param user
     * @return
     *     returns java.util.List<ru.runa.wfe.webservice.WfProcess>
     */
    @WebMethod
    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "getSubprocesses", targetNamespace = "http://impl.service.wfe.runa.ru/", className = "ru.runa.wfe.webservice.GetSubprocesses")
    @ResponseWrapper(localName = "getSubprocessesResponse", targetNamespace = "http://impl.service.wfe.runa.ru/", className = "ru.runa.wfe.webservice.GetSubprocessesResponse")
    public List<WfProcess> getSubprocesses(
        @WebParam(name = "user", targetNamespace = "")
        User user,
        @WebParam(name = "id", targetNamespace = "")
        Long id,
        @WebParam(name = "recursive", targetNamespace = "")
        boolean recursive);

    /**
     * 
     * @param processId
     * @param user
     */
    @WebMethod
    @RequestWrapper(localName = "cancelProcess", targetNamespace = "http://impl.service.wfe.runa.ru/", className = "ru.runa.wfe.webservice.CancelProcess")
    @ResponseWrapper(localName = "cancelProcessResponse", targetNamespace = "http://impl.service.wfe.runa.ru/", className = "ru.runa.wfe.webservice.CancelProcessResponse")
    public void cancelProcess(
        @WebParam(name = "user", targetNamespace = "")
        User user,
        @WebParam(name = "processId", targetNamespace = "")
        Long processId);

    /**
     * 
     * @param processId
     * @param user
     * @return
     *     returns java.util.List<ru.runa.wfe.webservice.WfSwimlane>
     */
    @WebMethod
    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "getSwimlanes", targetNamespace = "http://impl.service.wfe.runa.ru/", className = "ru.runa.wfe.webservice.GetSwimlanes")
    @ResponseWrapper(localName = "getSwimlanesResponse", targetNamespace = "http://impl.service.wfe.runa.ru/", className = "ru.runa.wfe.webservice.GetSwimlanesResponse")
    public List<WfSwimlane> getSwimlanes(
        @WebParam(name = "user", targetNamespace = "")
        User user,
        @WebParam(name = "processId", targetNamespace = "")
        Long processId);

    /**
     * 
     * @param childProcessId
     * @param taskId
     * @param processId
     * @param user
     * @param subprocessId
     * @return
     *     returns byte[]
     */
    @WebMethod
    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "getProcessDiagram", targetNamespace = "http://impl.service.wfe.runa.ru/", className = "ru.runa.wfe.webservice.GetProcessDiagram")
    @ResponseWrapper(localName = "getProcessDiagramResponse", targetNamespace = "http://impl.service.wfe.runa.ru/", className = "ru.runa.wfe.webservice.GetProcessDiagramResponse")
    public byte[] getProcessDiagram(
        @WebParam(name = "user", targetNamespace = "")
        User user,
        @WebParam(name = "processId", targetNamespace = "")
        Long processId,
        @WebParam(name = "taskId", targetNamespace = "")
        Long taskId,
        @WebParam(name = "childProcessId", targetNamespace = "")
        Long childProcessId,
        @WebParam(name = "subprocessId", targetNamespace = "")
        String subprocessId);

}
