
package ru.runa.wfe.webservice;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2-12/14/2009 02:16 PM(ramkris)-
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ExecutorAPI", targetNamespace = "http://impl.service.wfe.runa.ru/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ExecutorAPI {


    /**
     * 
     * @param ids
     * @param user
     */
    @WebMethod
    @RequestWrapper(localName = "remove", targetNamespace = "http://impl.service.wfe.runa.ru/", className = "ru.runa.wfe.webservice.Remove")
    @ResponseWrapper(localName = "removeResponse", targetNamespace = "http://impl.service.wfe.runa.ru/", className = "ru.runa.wfe.webservice.RemoveResponse")
    public void remove(
        @WebParam(name = "user", targetNamespace = "")
        User user,
        @WebParam(name = "ids", targetNamespace = "")
        List<Long> ids);

    /**
     * 
     * @param executor
     * @param user
     * @return
     *     returns ru.runa.wfe.webservice.WfExecutor
     */
    @WebMethod
    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "create", targetNamespace = "http://impl.service.wfe.runa.ru/", className = "ru.runa.wfe.webservice.Create")
    @ResponseWrapper(localName = "createResponse", targetNamespace = "http://impl.service.wfe.runa.ru/", className = "ru.runa.wfe.webservice.CreateResponse")
    public WfExecutor create(
        @WebParam(name = "user", targetNamespace = "")
        User user,
        @WebParam(name = "executor", targetNamespace = "")
        WfExecutor executor);

    /**
     * 
     * @param active
     * @param actor
     * @param user
     */
    @WebMethod
    @RequestWrapper(localName = "setStatus", targetNamespace = "http://impl.service.wfe.runa.ru/", className = "ru.runa.wfe.webservice.SetStatus")
    @ResponseWrapper(localName = "setStatusResponse", targetNamespace = "http://impl.service.wfe.runa.ru/", className = "ru.runa.wfe.webservice.SetStatusResponse")
    public void setStatus(
        @WebParam(name = "user", targetNamespace = "")
        User user,
        @WebParam(name = "actor", targetNamespace = "")
        Actor actor,
        @WebParam(name = "active", targetNamespace = "")
        boolean active);

    /**
     * 
     * @param user
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "isAdministrator", targetNamespace = "http://impl.service.wfe.runa.ru/", className = "ru.runa.wfe.webservice.IsAdministrator")
    @ResponseWrapper(localName = "isAdministratorResponse", targetNamespace = "http://impl.service.wfe.runa.ru/", className = "ru.runa.wfe.webservice.IsAdministratorResponse")
    public boolean isAdministrator(
        @WebParam(name = "user", targetNamespace = "")
        User user);

    /**
     * 
     * @param login
     * @return
     *     returns ru.runa.wfe.webservice.Actor
     */
    @WebMethod
    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "getActorCaseInsensitive", targetNamespace = "http://impl.service.wfe.runa.ru/", className = "ru.runa.wfe.webservice.GetActorCaseInsensitive")
    @ResponseWrapper(localName = "getActorCaseInsensitiveResponse", targetNamespace = "http://impl.service.wfe.runa.ru/", className = "ru.runa.wfe.webservice.GetActorCaseInsensitiveResponse")
    public Actor getActorCaseInsensitive(
        @WebParam(name = "login", targetNamespace = "")
        String login);

    /**
     * 
     * @param executorId
     * @param groupIds
     * @param user
     */
    @WebMethod
    @RequestWrapper(localName = "removeExecutorFromGroups", targetNamespace = "http://impl.service.wfe.runa.ru/", className = "ru.runa.wfe.webservice.RemoveExecutorFromGroups")
    @ResponseWrapper(localName = "removeExecutorFromGroupsResponse", targetNamespace = "http://impl.service.wfe.runa.ru/", className = "ru.runa.wfe.webservice.RemoveExecutorFromGroupsResponse")
    public void removeExecutorFromGroups(
        @WebParam(name = "user", targetNamespace = "")
        User user,
        @WebParam(name = "executorId", targetNamespace = "")
        Long executorId,
        @WebParam(name = "groupIds", targetNamespace = "")
        List<Long> groupIds);

    /**
     * 
     * @param groupId
     * @param user
     * @param executorIds
     */
    @WebMethod
    @RequestWrapper(localName = "addExecutorsToGroup", targetNamespace = "http://impl.service.wfe.runa.ru/", className = "ru.runa.wfe.webservice.AddExecutorsToGroup")
    @ResponseWrapper(localName = "addExecutorsToGroupResponse", targetNamespace = "http://impl.service.wfe.runa.ru/", className = "ru.runa.wfe.webservice.AddExecutorsToGroupResponse")
    public void addExecutorsToGroup(
        @WebParam(name = "user", targetNamespace = "")
        User user,
        @WebParam(name = "executorIds", targetNamespace = "")
        List<Long> executorIds,
        @WebParam(name = "groupId", targetNamespace = "")
        Long groupId);

    /**
     * 
     * @param executor
     * @param group
     * @param user
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "isExecutorInGroup", targetNamespace = "http://impl.service.wfe.runa.ru/", className = "ru.runa.wfe.webservice.IsExecutorInGroup")
    @ResponseWrapper(localName = "isExecutorInGroupResponse", targetNamespace = "http://impl.service.wfe.runa.ru/", className = "ru.runa.wfe.webservice.IsExecutorInGroupResponse")
    public boolean isExecutorInGroup(
        @WebParam(name = "user", targetNamespace = "")
        User user,
        @WebParam(name = "executor", targetNamespace = "")
        WfExecutor executor,
        @WebParam(name = "group", targetNamespace = "")
        Group group);

    /**
     * 
     * @param excluded
     * @param executor
     * @param batchPresentation
     * @param user
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "getExecutorGroupsCount", targetNamespace = "http://impl.service.wfe.runa.ru/", className = "ru.runa.wfe.webservice.GetExecutorGroupsCount")
    @ResponseWrapper(localName = "getExecutorGroupsCountResponse", targetNamespace = "http://impl.service.wfe.runa.ru/", className = "ru.runa.wfe.webservice.GetExecutorGroupsCountResponse")
    public int getExecutorGroupsCount(
        @WebParam(name = "user", targetNamespace = "")
        User user,
        @WebParam(name = "executor", targetNamespace = "")
        WfExecutor executor,
        @WebParam(name = "batchPresentation", targetNamespace = "")
        BatchPresentation batchPresentation,
        @WebParam(name = "excluded", targetNamespace = "")
        boolean excluded);

    /**
     * 
     * @param name
     * @param user
     * @return
     *     returns ru.runa.wfe.webservice.WfExecutor
     */
    @WebMethod
    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "getExecutorByName", targetNamespace = "http://impl.service.wfe.runa.ru/", className = "ru.runa.wfe.webservice.GetExecutorByName")
    @ResponseWrapper(localName = "getExecutorByNameResponse", targetNamespace = "http://impl.service.wfe.runa.ru/", className = "ru.runa.wfe.webservice.GetExecutorByNameResponse")
    public WfExecutor getExecutorByName(
        @WebParam(name = "user", targetNamespace = "")
        User user,
        @WebParam(name = "name", targetNamespace = "")
        String name);

    /**
     * 
     * @param user
     * @param executorName
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "isExecutorExist", targetNamespace = "http://impl.service.wfe.runa.ru/", className = "ru.runa.wfe.webservice.IsExecutorExist")
    @ResponseWrapper(localName = "isExecutorExistResponse", targetNamespace = "http://impl.service.wfe.runa.ru/", className = "ru.runa.wfe.webservice.IsExecutorExistResponse")
    public boolean isExecutorExist(
        @WebParam(name = "user", targetNamespace = "")
        User user,
        @WebParam(name = "executorName", targetNamespace = "")
        String executorName);

    /**
     * 
     * @param excluded
     * @param batchPresentation
     * @param group
     * @param user
     * @return
     *     returns java.util.List<ru.runa.wfe.webservice.WfExecutor>
     */
    @WebMethod
    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "getGroupChildren", targetNamespace = "http://impl.service.wfe.runa.ru/", className = "ru.runa.wfe.webservice.GetGroupChildren")
    @ResponseWrapper(localName = "getGroupChildrenResponse", targetNamespace = "http://impl.service.wfe.runa.ru/", className = "ru.runa.wfe.webservice.GetGroupChildrenResponse")
    public List<WfExecutor> getGroupChildren(
        @WebParam(name = "user", targetNamespace = "")
        User user,
        @WebParam(name = "group", targetNamespace = "")
        Group group,
        @WebParam(name = "batchPresentation", targetNamespace = "")
        BatchPresentation batchPresentation,
        @WebParam(name = "excluded", targetNamespace = "")
        boolean excluded);

    /**
     * 
     * @param id
     * @param user
     * @return
     *     returns ru.runa.wfe.webservice.WfExecutor
     */
    @WebMethod
    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "getExecutor", targetNamespace = "http://impl.service.wfe.runa.ru/", className = "ru.runa.wfe.webservice.GetExecutor")
    @ResponseWrapper(localName = "getExecutorResponse", targetNamespace = "http://impl.service.wfe.runa.ru/", className = "ru.runa.wfe.webservice.GetExecutorResponse")
    public WfExecutor getExecutor(
        @WebParam(name = "user", targetNamespace = "")
        User user,
        @WebParam(name = "id", targetNamespace = "")
        Long id);

    /**
     * 
     * @param executorId
     * @param groupIds
     * @param user
     */
    @WebMethod
    @RequestWrapper(localName = "addExecutorToGroups", targetNamespace = "http://impl.service.wfe.runa.ru/", className = "ru.runa.wfe.webservice.AddExecutorToGroups")
    @ResponseWrapper(localName = "addExecutorToGroupsResponse", targetNamespace = "http://impl.service.wfe.runa.ru/", className = "ru.runa.wfe.webservice.AddExecutorToGroupsResponse")
    public void addExecutorToGroups(
        @WebParam(name = "user", targetNamespace = "")
        User user,
        @WebParam(name = "executorId", targetNamespace = "")
        Long executorId,
        @WebParam(name = "groupIds", targetNamespace = "")
        List<Long> groupIds);

    /**
     * 
     * @param actor
     * @param password
     * @param user
     */
    @WebMethod
    @RequestWrapper(localName = "setPassword", targetNamespace = "http://impl.service.wfe.runa.ru/", className = "ru.runa.wfe.webservice.SetPassword")
    @ResponseWrapper(localName = "setPasswordResponse", targetNamespace = "http://impl.service.wfe.runa.ru/", className = "ru.runa.wfe.webservice.SetPasswordResponse")
    public void setPassword(
        @WebParam(name = "user", targetNamespace = "")
        User user,
        @WebParam(name = "actor", targetNamespace = "")
        Actor actor,
        @WebParam(name = "password", targetNamespace = "")
        String password);

    /**
     * 
     * @param executor
     * @param user
     */
    @WebMethod
    @RequestWrapper(localName = "update", targetNamespace = "http://impl.service.wfe.runa.ru/", className = "ru.runa.wfe.webservice.Update")
    @ResponseWrapper(localName = "updateResponse", targetNamespace = "http://impl.service.wfe.runa.ru/", className = "ru.runa.wfe.webservice.UpdateResponse")
    public void update(
        @WebParam(name = "user", targetNamespace = "")
        User user,
        @WebParam(name = "executor", targetNamespace = "")
        WfExecutor executor);

    /**
     * 
     * @param batchPresentation
     * @param user
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "getExecutorsCount", targetNamespace = "http://impl.service.wfe.runa.ru/", className = "ru.runa.wfe.webservice.GetExecutorsCount")
    @ResponseWrapper(localName = "getExecutorsCountResponse", targetNamespace = "http://impl.service.wfe.runa.ru/", className = "ru.runa.wfe.webservice.GetExecutorsCountResponse")
    public int getExecutorsCount(
        @WebParam(name = "user", targetNamespace = "")
        User user,
        @WebParam(name = "batchPresentation", targetNamespace = "")
        BatchPresentation batchPresentation);

    /**
     * 
     * @param excluded
     * @param batchPresentation
     * @param group
     * @param user
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "getGroupChildrenCount", targetNamespace = "http://impl.service.wfe.runa.ru/", className = "ru.runa.wfe.webservice.GetGroupChildrenCount")
    @ResponseWrapper(localName = "getGroupChildrenCountResponse", targetNamespace = "http://impl.service.wfe.runa.ru/", className = "ru.runa.wfe.webservice.GetGroupChildrenCountResponse")
    public int getGroupChildrenCount(
        @WebParam(name = "user", targetNamespace = "")
        User user,
        @WebParam(name = "group", targetNamespace = "")
        Group group,
        @WebParam(name = "batchPresentation", targetNamespace = "")
        BatchPresentation batchPresentation,
        @WebParam(name = "excluded", targetNamespace = "")
        boolean excluded);

    /**
     * 
     * @param group
     * @param user
     * @return
     *     returns java.util.List<ru.runa.wfe.webservice.WfExecutor>
     */
    @WebMethod
    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "getAllExecutorsFromGroup", targetNamespace = "http://impl.service.wfe.runa.ru/", className = "ru.runa.wfe.webservice.GetAllExecutorsFromGroup")
    @ResponseWrapper(localName = "getAllExecutorsFromGroupResponse", targetNamespace = "http://impl.service.wfe.runa.ru/", className = "ru.runa.wfe.webservice.GetAllExecutorsFromGroupResponse")
    public List<WfExecutor> getAllExecutorsFromGroup(
        @WebParam(name = "user", targetNamespace = "")
        User user,
        @WebParam(name = "group", targetNamespace = "")
        Group group);

    /**
     * 
     * @param groupId
     * @param user
     * @param executorIds
     */
    @WebMethod
    @RequestWrapper(localName = "removeExecutorsFromGroup", targetNamespace = "http://impl.service.wfe.runa.ru/", className = "ru.runa.wfe.webservice.RemoveExecutorsFromGroup")
    @ResponseWrapper(localName = "removeExecutorsFromGroupResponse", targetNamespace = "http://impl.service.wfe.runa.ru/", className = "ru.runa.wfe.webservice.RemoveExecutorsFromGroupResponse")
    public void removeExecutorsFromGroup(
        @WebParam(name = "user", targetNamespace = "")
        User user,
        @WebParam(name = "executorIds", targetNamespace = "")
        List<Long> executorIds,
        @WebParam(name = "groupId", targetNamespace = "")
        Long groupId);

    /**
     * 
     * @param code
     * @param user
     * @return
     *     returns ru.runa.wfe.webservice.Actor
     */
    @WebMethod
    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "getActorByCode", targetNamespace = "http://impl.service.wfe.runa.ru/", className = "ru.runa.wfe.webservice.GetActorByCode")
    @ResponseWrapper(localName = "getActorByCodeResponse", targetNamespace = "http://impl.service.wfe.runa.ru/", className = "ru.runa.wfe.webservice.GetActorByCodeResponse")
    public Actor getActorByCode(
        @WebParam(name = "user", targetNamespace = "")
        User user,
        @WebParam(name = "code", targetNamespace = "")
        Long code);

    /**
     * 
     * @param excluded
     * @param executor
     * @param batchPresentation
     * @param user
     * @return
     *     returns java.util.List<ru.runa.wfe.webservice.Group>
     */
    @WebMethod
    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "getExecutorGroups", targetNamespace = "http://impl.service.wfe.runa.ru/", className = "ru.runa.wfe.webservice.GetExecutorGroups")
    @ResponseWrapper(localName = "getExecutorGroupsResponse", targetNamespace = "http://impl.service.wfe.runa.ru/", className = "ru.runa.wfe.webservice.GetExecutorGroupsResponse")
    public List<Group> getExecutorGroups(
        @WebParam(name = "user", targetNamespace = "")
        User user,
        @WebParam(name = "executor", targetNamespace = "")
        WfExecutor executor,
        @WebParam(name = "batchPresentation", targetNamespace = "")
        BatchPresentation batchPresentation,
        @WebParam(name = "excluded", targetNamespace = "")
        boolean excluded);

    /**
     * 
     * @param batchPresentation
     * @param user
     * @return
     *     returns java.util.List<java.lang.Object>
     */
    @WebMethod
    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "getExecutors", targetNamespace = "http://impl.service.wfe.runa.ru/", className = "ru.runa.wfe.webservice.GetExecutors")
    @ResponseWrapper(localName = "getExecutorsResponse", targetNamespace = "http://impl.service.wfe.runa.ru/", className = "ru.runa.wfe.webservice.GetExecutorsResponse")
    public List<Object> getExecutors(
        @WebParam(name = "user", targetNamespace = "")
        User user,
        @WebParam(name = "batchPresentation", targetNamespace = "")
        BatchPresentation batchPresentation);

    /**
     * 
     * @param group
     * @param user
     * @return
     *     returns java.util.List<ru.runa.wfe.webservice.Actor>
     */
    @WebMethod
    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "getGroupActors", targetNamespace = "http://impl.service.wfe.runa.ru/", className = "ru.runa.wfe.webservice.GetGroupActors")
    @ResponseWrapper(localName = "getGroupActorsResponse", targetNamespace = "http://impl.service.wfe.runa.ru/", className = "ru.runa.wfe.webservice.GetGroupActorsResponse")
    public List<Actor> getGroupActors(
        @WebParam(name = "user", targetNamespace = "")
        User user,
        @WebParam(name = "group", targetNamespace = "")
        Group group);

}
