
package ru.runa.wfe.webservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2-12/14/2009 02:16 PM(ramkris)-
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "RelationWebService", targetNamespace = "http://impl.service.wfe.runa.ru/", wsdlLocation = "http://localhost:8080/wfe-service-4.3.0-SNAPSHOT/RelationWebService/RelationAPI?wsdl")
public class RelationWebService
    extends Service
{

    private final static URL RELATIONWEBSERVICE_WSDL_LOCATION;
    private final static WebServiceException RELATIONWEBSERVICE_EXCEPTION;
    private final static QName RELATIONWEBSERVICE_QNAME = new QName("http://impl.service.wfe.runa.ru/", "RelationWebService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/wfe-service-4.3.0-SNAPSHOT/RelationWebService/RelationAPI?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        RELATIONWEBSERVICE_WSDL_LOCATION = url;
        RELATIONWEBSERVICE_EXCEPTION = e;
    }

    public RelationWebService() {
        super(__getWsdlLocation(), RELATIONWEBSERVICE_QNAME);
    }

    public RelationWebService(WebServiceFeature... features) {
        super(__getWsdlLocation(), RELATIONWEBSERVICE_QNAME, features);
    }

    public RelationWebService(URL wsdlLocation) {
        super(wsdlLocation, RELATIONWEBSERVICE_QNAME);
    }

    public RelationWebService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, RELATIONWEBSERVICE_QNAME, features);
    }

    public RelationWebService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public RelationWebService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns RelationAPI
     */
    @WebEndpoint(name = "RelationAPIPort")
    public RelationAPI getRelationAPIPort() {
        return super.getPort(new QName("http://impl.service.wfe.runa.ru/", "RelationAPIPort"), RelationAPI.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns RelationAPI
     */
    @WebEndpoint(name = "RelationAPIPort")
    public RelationAPI getRelationAPIPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://impl.service.wfe.runa.ru/", "RelationAPIPort"), RelationAPI.class, features);
    }

    private static URL __getWsdlLocation() {
        if (RELATIONWEBSERVICE_EXCEPTION!= null) {
            throw RELATIONWEBSERVICE_EXCEPTION;
        }
        return RELATIONWEBSERVICE_WSDL_LOCATION;
    }

}
