
package ru.runa.wfe.webservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2-12/14/2009 02:16 PM(ramkris)-
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ScriptingWebService", targetNamespace = "http://impl.service.wfe.runa.ru/", wsdlLocation = "http://localhost:8080/wfe-service-4.3.0-SNAPSHOT/ScriptingWebService/ScriptingAPI?wsdl")
public class ScriptingWebService
    extends Service
{

    private final static URL SCRIPTINGWEBSERVICE_WSDL_LOCATION;
    private final static WebServiceException SCRIPTINGWEBSERVICE_EXCEPTION;
    private final static QName SCRIPTINGWEBSERVICE_QNAME = new QName("http://impl.service.wfe.runa.ru/", "ScriptingWebService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/wfe-service-4.3.0-SNAPSHOT/ScriptingWebService/ScriptingAPI?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SCRIPTINGWEBSERVICE_WSDL_LOCATION = url;
        SCRIPTINGWEBSERVICE_EXCEPTION = e;
    }

    public ScriptingWebService() {
        super(__getWsdlLocation(), SCRIPTINGWEBSERVICE_QNAME);
    }

    public ScriptingWebService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SCRIPTINGWEBSERVICE_QNAME, features);
    }

    public ScriptingWebService(URL wsdlLocation) {
        super(wsdlLocation, SCRIPTINGWEBSERVICE_QNAME);
    }

    public ScriptingWebService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SCRIPTINGWEBSERVICE_QNAME, features);
    }

    public ScriptingWebService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ScriptingWebService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ScriptingAPI
     */
    @WebEndpoint(name = "ScriptingAPIPort")
    public ScriptingAPI getScriptingAPIPort() {
        return super.getPort(new QName("http://impl.service.wfe.runa.ru/", "ScriptingAPIPort"), ScriptingAPI.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ScriptingAPI
     */
    @WebEndpoint(name = "ScriptingAPIPort")
    public ScriptingAPI getScriptingAPIPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://impl.service.wfe.runa.ru/", "ScriptingAPIPort"), ScriptingAPI.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SCRIPTINGWEBSERVICE_EXCEPTION!= null) {
            throw SCRIPTINGWEBSERVICE_EXCEPTION;
        }
        return SCRIPTINGWEBSERVICE_WSDL_LOCATION;
    }

}
