
package ru.runa.wfe.webservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2-12/14/2009 02:16 PM(ramkris)-
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ScriptingAPI", targetNamespace = "http://impl.service.wfe.runa.ru/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ScriptingAPI {


    /**
     * 
     * @param script
     * @param user
     */
    @WebMethod
    @RequestWrapper(localName = "executeGroovyScript", targetNamespace = "http://impl.service.wfe.runa.ru/", className = "ru.runa.wfe.webservice.ExecuteGroovyScript")
    @ResponseWrapper(localName = "executeGroovyScriptResponse", targetNamespace = "http://impl.service.wfe.runa.ru/", className = "ru.runa.wfe.webservice.ExecuteGroovyScriptResponse")
    public void executeGroovyScript(
        @WebParam(name = "user", targetNamespace = "")
        User user,
        @WebParam(name = "script", targetNamespace = "")
        String script);

}
