
package ru.runa.wfe.webservice;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2-12/14/2009 02:16 PM(ramkris)-
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SubstitutionAPI", targetNamespace = "http://impl.service.wfe.runa.ru/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SubstitutionAPI {


    /**
     * 
     * @param substitution
     * @param user
     * @return
     *     returns ru.runa.wfe.webservice.Substitution
     */
    @WebMethod
    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "createSubstitution", targetNamespace = "http://impl.service.wfe.runa.ru/", className = "ru.runa.wfe.webservice.CreateSubstitution")
    @ResponseWrapper(localName = "createSubstitutionResponse", targetNamespace = "http://impl.service.wfe.runa.ru/", className = "ru.runa.wfe.webservice.CreateSubstitutionResponse")
    public Substitution createSubstitution(
        @WebParam(name = "user", targetNamespace = "")
        User user,
        @WebParam(name = "substitution", targetNamespace = "")
        Substitution substitution);

    /**
     * 
     * @param user
     * @param substitutionCriteria
     */
    @WebMethod
    @RequestWrapper(localName = "createCriteria", targetNamespace = "http://impl.service.wfe.runa.ru/", className = "ru.runa.wfe.webservice.CreateCriteria")
    @ResponseWrapper(localName = "createCriteriaResponse", targetNamespace = "http://impl.service.wfe.runa.ru/", className = "ru.runa.wfe.webservice.CreateCriteriaResponse")
    public void createCriteria(
        @WebParam(name = "user", targetNamespace = "")
        User user,
        @WebParam(name = "substitutionCriteria", targetNamespace = "")
        SubstitutionCriteria substitutionCriteria);

    /**
     * 
     * @param user
     * @param substitutionCriteria
     * @return
     *     returns java.util.List<ru.runa.wfe.webservice.Substitution>
     */
    @WebMethod
    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "getSubstitutionsByCriteria", targetNamespace = "http://impl.service.wfe.runa.ru/", className = "ru.runa.wfe.webservice.GetSubstitutionsByCriteria")
    @ResponseWrapper(localName = "getSubstitutionsByCriteriaResponse", targetNamespace = "http://impl.service.wfe.runa.ru/", className = "ru.runa.wfe.webservice.GetSubstitutionsByCriteriaResponse")
    public List<Substitution> getSubstitutionsByCriteria(
        @WebParam(name = "user", targetNamespace = "")
        User user,
        @WebParam(name = "substitutionCriteria", targetNamespace = "")
        SubstitutionCriteria substitutionCriteria);

    /**
     * 
     * @param substitutionId
     * @param user
     * @return
     *     returns ru.runa.wfe.webservice.Substitution
     */
    @WebMethod
    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "getSubstitution", targetNamespace = "http://impl.service.wfe.runa.ru/", className = "ru.runa.wfe.webservice.GetSubstitution")
    @ResponseWrapper(localName = "getSubstitutionResponse", targetNamespace = "http://impl.service.wfe.runa.ru/", className = "ru.runa.wfe.webservice.GetSubstitutionResponse")
    public Substitution getSubstitution(
        @WebParam(name = "user", targetNamespace = "")
        User user,
        @WebParam(name = "substitutionId", targetNamespace = "")
        Long substitutionId);

    /**
     * 
     * @param user
     * @param substitutionCriteria
     */
    @WebMethod
    @RequestWrapper(localName = "deleteCriteria", targetNamespace = "http://impl.service.wfe.runa.ru/", className = "ru.runa.wfe.webservice.DeleteCriteria")
    @ResponseWrapper(localName = "deleteCriteriaResponse", targetNamespace = "http://impl.service.wfe.runa.ru/", className = "ru.runa.wfe.webservice.DeleteCriteriaResponse")
    public void deleteCriteria(
        @WebParam(name = "user", targetNamespace = "")
        User user,
        @WebParam(name = "substitutionCriteria", targetNamespace = "")
        SubstitutionCriteria substitutionCriteria);

    /**
     * 
     * @param substitutionIds
     * @param user
     */
    @WebMethod
    @RequestWrapper(localName = "deleteSubstitutions", targetNamespace = "http://impl.service.wfe.runa.ru/", className = "ru.runa.wfe.webservice.DeleteSubstitutions")
    @ResponseWrapper(localName = "deleteSubstitutionsResponse", targetNamespace = "http://impl.service.wfe.runa.ru/", className = "ru.runa.wfe.webservice.DeleteSubstitutionsResponse")
    public void deleteSubstitutions(
        @WebParam(name = "user", targetNamespace = "")
        User user,
        @WebParam(name = "substitutionIds", targetNamespace = "")
        List<Long> substitutionIds);

    /**
     * 
     * @param user
     * @param substitutionCriteria
     */
    @WebMethod
    @RequestWrapper(localName = "updateCriteria", targetNamespace = "http://impl.service.wfe.runa.ru/", className = "ru.runa.wfe.webservice.UpdateCriteria")
    @ResponseWrapper(localName = "updateCriteriaResponse", targetNamespace = "http://impl.service.wfe.runa.ru/", className = "ru.runa.wfe.webservice.UpdateCriteriaResponse")
    public void updateCriteria(
        @WebParam(name = "user", targetNamespace = "")
        User user,
        @WebParam(name = "substitutionCriteria", targetNamespace = "")
        SubstitutionCriteria substitutionCriteria);

    /**
     * 
     * @param criterias
     * @param user
     */
    @WebMethod
    @RequestWrapper(localName = "deleteCriterias", targetNamespace = "http://impl.service.wfe.runa.ru/", className = "ru.runa.wfe.webservice.DeleteCriterias")
    @ResponseWrapper(localName = "deleteCriteriasResponse", targetNamespace = "http://impl.service.wfe.runa.ru/", className = "ru.runa.wfe.webservice.DeleteCriteriasResponse")
    public void deleteCriterias(
        @WebParam(name = "user", targetNamespace = "")
        User user,
        @WebParam(name = "criterias", targetNamespace = "")
        List<SubstitutionCriteria> criterias);

    /**
     * 
     * @param user
     * @return
     *     returns java.util.List<ru.runa.wfe.webservice.SubstitutionCriteria>
     */
    @WebMethod
    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "getAllCriterias", targetNamespace = "http://impl.service.wfe.runa.ru/", className = "ru.runa.wfe.webservice.GetAllCriterias")
    @ResponseWrapper(localName = "getAllCriteriasResponse", targetNamespace = "http://impl.service.wfe.runa.ru/", className = "ru.runa.wfe.webservice.GetAllCriteriasResponse")
    public List<SubstitutionCriteria> getAllCriterias(
        @WebParam(name = "user", targetNamespace = "")
        User user);

    /**
     * 
     * @param name
     * @param user
     * @return
     *     returns ru.runa.wfe.webservice.SubstitutionCriteria
     */
    @WebMethod
    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "getCriteriaByName", targetNamespace = "http://impl.service.wfe.runa.ru/", className = "ru.runa.wfe.webservice.GetCriteriaByName")
    @ResponseWrapper(localName = "getCriteriaByNameResponse", targetNamespace = "http://impl.service.wfe.runa.ru/", className = "ru.runa.wfe.webservice.GetCriteriaByNameResponse")
    public SubstitutionCriteria getCriteriaByName(
        @WebParam(name = "user", targetNamespace = "")
        User user,
        @WebParam(name = "name", targetNamespace = "")
        String name);

    /**
     * 
     * @param user
     * @param substitutionCriteriaId
     * @return
     *     returns ru.runa.wfe.webservice.SubstitutionCriteria
     */
    @WebMethod
    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "getCriteria", targetNamespace = "http://impl.service.wfe.runa.ru/", className = "ru.runa.wfe.webservice.GetCriteria")
    @ResponseWrapper(localName = "getCriteriaResponse", targetNamespace = "http://impl.service.wfe.runa.ru/", className = "ru.runa.wfe.webservice.GetCriteriaResponse")
    public SubstitutionCriteria getCriteria(
        @WebParam(name = "user", targetNamespace = "")
        User user,
        @WebParam(name = "substitutionCriteriaId", targetNamespace = "")
        Long substitutionCriteriaId);

    /**
     * 
     * @param substitution
     * @param user
     */
    @WebMethod
    @RequestWrapper(localName = "updateSubstitution", targetNamespace = "http://impl.service.wfe.runa.ru/", className = "ru.runa.wfe.webservice.UpdateSubstitution")
    @ResponseWrapper(localName = "updateSubstitutionResponse", targetNamespace = "http://impl.service.wfe.runa.ru/", className = "ru.runa.wfe.webservice.UpdateSubstitutionResponse")
    public void updateSubstitution(
        @WebParam(name = "user", targetNamespace = "")
        User user,
        @WebParam(name = "substitution", targetNamespace = "")
        Substitution substitution);

    /**
     * 
     * @param actorId
     * @param user
     * @return
     *     returns java.util.List<ru.runa.wfe.webservice.Substitution>
     */
    @WebMethod
    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "getSubstitutions", targetNamespace = "http://impl.service.wfe.runa.ru/", className = "ru.runa.wfe.webservice.GetSubstitutions")
    @ResponseWrapper(localName = "getSubstitutionsResponse", targetNamespace = "http://impl.service.wfe.runa.ru/", className = "ru.runa.wfe.webservice.GetSubstitutionsResponse")
    public List<Substitution> getSubstitutions(
        @WebParam(name = "user", targetNamespace = "")
        User user,
        @WebParam(name = "actorId", targetNamespace = "")
        Long actorId);

}
