
package ru.runa.wfe.webservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2-12/14/2009 02:16 PM(ramkris)-
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SubstitutionWebService", targetNamespace = "http://impl.service.wfe.runa.ru/", wsdlLocation = "http://localhost:8080/wfe-service-4.3.0-SNAPSHOT/SubstitutionWebService/SubstitutionAPI?wsdl")
public class SubstitutionWebService
    extends Service
{

    private final static URL SUBSTITUTIONWEBSERVICE_WSDL_LOCATION;
    private final static WebServiceException SUBSTITUTIONWEBSERVICE_EXCEPTION;
    private final static QName SUBSTITUTIONWEBSERVICE_QNAME = new QName("http://impl.service.wfe.runa.ru/", "SubstitutionWebService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/wfe-service-4.3.0-SNAPSHOT/SubstitutionWebService/SubstitutionAPI?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SUBSTITUTIONWEBSERVICE_WSDL_LOCATION = url;
        SUBSTITUTIONWEBSERVICE_EXCEPTION = e;
    }

    public SubstitutionWebService() {
        super(__getWsdlLocation(), SUBSTITUTIONWEBSERVICE_QNAME);
    }

    public SubstitutionWebService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SUBSTITUTIONWEBSERVICE_QNAME, features);
    }

    public SubstitutionWebService(URL wsdlLocation) {
        super(wsdlLocation, SUBSTITUTIONWEBSERVICE_QNAME);
    }

    public SubstitutionWebService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SUBSTITUTIONWEBSERVICE_QNAME, features);
    }

    public SubstitutionWebService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SubstitutionWebService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SubstitutionAPI
     */
    @WebEndpoint(name = "SubstitutionAPIPort")
    public SubstitutionAPI getSubstitutionAPIPort() {
        return super.getPort(new QName("http://impl.service.wfe.runa.ru/", "SubstitutionAPIPort"), SubstitutionAPI.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SubstitutionAPI
     */
    @WebEndpoint(name = "SubstitutionAPIPort")
    public SubstitutionAPI getSubstitutionAPIPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://impl.service.wfe.runa.ru/", "SubstitutionAPIPort"), SubstitutionAPI.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SUBSTITUTIONWEBSERVICE_EXCEPTION!= null) {
            throw SUBSTITUTIONWEBSERVICE_EXCEPTION;
        }
        return SUBSTITUTIONWEBSERVICE_WSDL_LOCATION;
    }

}
