
package ru.runa.wfe.webservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2-12/14/2009 02:16 PM(ramkris)-
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "TaskWebService", targetNamespace = "http://impl.service.wfe.runa.ru/", wsdlLocation = "http://localhost:8080/wfe-service-4.3.0-SNAPSHOT/TaskWebService/TaskAPI?wsdl")
public class TaskWebService
    extends Service
{

    private final static URL TASKWEBSERVICE_WSDL_LOCATION;
    private final static WebServiceException TASKWEBSERVICE_EXCEPTION;
    private final static QName TASKWEBSERVICE_QNAME = new QName("http://impl.service.wfe.runa.ru/", "TaskWebService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/wfe-service-4.3.0-SNAPSHOT/TaskWebService/TaskAPI?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        TASKWEBSERVICE_WSDL_LOCATION = url;
        TASKWEBSERVICE_EXCEPTION = e;
    }

    public TaskWebService() {
        super(__getWsdlLocation(), TASKWEBSERVICE_QNAME);
    }

    public TaskWebService(WebServiceFeature... features) {
        super(__getWsdlLocation(), TASKWEBSERVICE_QNAME, features);
    }

    public TaskWebService(URL wsdlLocation) {
        super(wsdlLocation, TASKWEBSERVICE_QNAME);
    }

    public TaskWebService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, TASKWEBSERVICE_QNAME, features);
    }

    public TaskWebService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TaskWebService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns TaskAPI
     */
    @WebEndpoint(name = "TaskAPIPort")
    public TaskAPI getTaskAPIPort() {
        return super.getPort(new QName("http://impl.service.wfe.runa.ru/", "TaskAPIPort"), TaskAPI.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TaskAPI
     */
    @WebEndpoint(name = "TaskAPIPort")
    public TaskAPI getTaskAPIPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://impl.service.wfe.runa.ru/", "TaskAPIPort"), TaskAPI.class, features);
    }

    private static URL __getWsdlLocation() {
        if (TASKWEBSERVICE_EXCEPTION!= null) {
            throw TASKWEBSERVICE_EXCEPTION;
        }
        return TASKWEBSERVICE_WSDL_LOCATION;
    }

}
