import { type AppTheme } from '../ts/app-theme'

export const themes: Readonly<{ [name: string]: AppTheme }> = Object.freeze({
  gray: {
    label: 'Серая',
    logo: 'logo-blue.svg',
    navBarContrast: {
      light: 'light',
      dark: 'dark',
    },
     light: {
       primary: '#AAAAAA',
       secondary: '#F3F3F3',
       accent: '#262626',
       error: '#D53525',
       info: '#A0CDE8',
       success: '#63CC78',
       warning: '#DDBB99',
       'primary-background': '#FFFFFF',
       'primary-background-darken-1': '#F8F8FA',
       'primary-text': '#262626',
       'secondary-text': '#777',
       'nav-bar': '#DDDDDD',
       'task-expiration': '#FF9999',
       'task-escalation': '#EF8FF8',
       'task-delegation': '#7FFFD4',
       'task-substitution': '#ffff9d',
     },
     dark: {
       primary: '#757575',
       secondary: '#4D4D4D',
       accent: '#EEEEEE',
       error: '#972020',
       info: '#345DD8',
       success: '#1CC754',
       warning: '#623C0D',
       'nav-bar': '#262626',
       'primary-background': '#2A2A2A',
       'primary-background-darken-1': '#333333',
       'primary-text': '#EEEEEE',
       'secondary-text': '#BBB',
       'task-expiration': '#972020',
       'task-escalation': '#8A578E',
       'task-delegation': '#529B83',
       'task-substitution': '#9E9E60',
     },
   },
   blue: {
     label: 'Синяя',
     logo: 'logo-blue.svg',
     navBarContrast: {
       light: 'light',
       dark: 'dark',
     },
     light: {
       primary: '#3280D1',
       secondary: '#E6EEF7',
       accent: '#071B3D',
       error: '#D53525',
       info: '#A0CDE8',
       success: '#63CC78',
       warning: '#DDBB99',
       'nav-bar': '#BFD5EC',
       'primary-background': '#FFFFFF',
       'primary-background-darken-1': '#F3F7FB',
       'primary-text': '#071B3D',
       'secondary-text': '#777',
       'task-expiration': '#FF9999',
       'task-escalation': '#EF8FF8',
       'task-delegation': '#7FFFD4',
       'task-substitution': '#FFFF9D',
     },
     dark: {
       primary: '#2666A9',
       secondary: '#2666A9',
       accent: '#E6EEF7',
       error: '#972020',
       info: '#2666A9',
       success: '#1CC754',
       warning: '#623C0D',
       'nav-bar': '#071B3D',
       'primary-background': '#071B3D',
       'primary-background-darken-1': '#070B4A',
       'primary-text': '#FFFFFF',
       'secondary-text': '#BBB',
       'task-expiration': '#972020',
       'task-escalation': '#8A578E',
       'task-delegation': '#529B83',
       'task-substitution': '#9E9E60',
     },
   },
   greenInvert: {
     label: 'Зеленая инверт',
     logo: 'logo-mono.svg',
     navBarContrast: {
       light: 'dark',
       dark: 'dark',
     },
     light: {
       primary: '#73B07E',
       secondary: '#EFEFEF',
       accent: '#1C2230',
       error: '#D53525',
       info: '#A0CDE8',
       success: '#63CC78',
       warning: '#DDBB99',
       'nav-bar': '#1C2230',
       'primary-background': '#FFFFFF',
       'primary-background-darken-1': '#F8F8F8',
       'primary-text': '#262626',
       'secondary-text': '#777',
       'task-expiration': '#FF9999',
       'task-escalation': '#EF8FF8',
       'task-delegation': '#7FFFD4',
       'task-substitution': '#FFFF9D',
     },
     dark: {
       primary: '#43874E',
       secondary: '#47474E',
       accent: '#E3FFE0',
       error: '#972020',
       info: '#345DD8',
       success: '#1CC754',
       warning: '#623C0D',
       'nav-bar': '#2E2E32',
       'primary-background': '#2E2E32',
       'primary-background-darken-1': '#353539',
       'primary-text': '#FFFFFF',
       'secondary-text': '#BBB',
       'task-expiration': '#972020',
       'task-escalation': '#8A578E',
       'task-delegation': '#529B83',
       'task-substitution': '#9E9E60',
       surface: '#1D1D1F',
     },
   },
   blueInvert: {
     label: 'Синяя инверт',
     logo: 'logo-blue.svg',
     navBarContrast: {
       light: 'dark',
       dark: 'light',
     },
     light: {
       primary: '#3F51B5',
       secondary: '#EFEFEF',
       accent: '#1C2230',
       error: '#D53525',
       info: '#A0CDE8',
       success: '#63CC78',
       warning: '#DDBB99',
       'nav-bar': '#1C2230',
       'primary-background': '#FFFFFF',
       'primary-background-darken-1': '#F8F8F8',
       'primary-text': '#262626',
       'secondary-text': '#777',
       'task-expiration': '#FF9999',
       'task-escalation': '#EF8FF8',
       'task-delegation': '#7FFFD4',
       'task-substitution': '#ffff9d',
     },
     dark: {
       primary: '#5b9ce5',
       secondary: '#444444',
       accent: '#E6E9F4',
       error: '#972020',
       info: '#345DD8',
       success: '#1CC754',
       warning: '#623C0D',
       'nav-bar': 'B0B0B0',
       'primary-background': '#2F2F2F',
       'primary-background-darken-1': '#353535',
       'primary-text': '#FFFFFF',
       'secondary-text': '#BBB',
       'task-expiration': '#972020',
       'task-escalation': '#8A578E',
       'task-delegation': '#529B83',
       'task-substitution': '#9E9E60',
     },
   },
})
