//
// ATTENTION!!! This file is auto-generated by wfe-codegen-dbaware subproject. See README.txt there.
//
// UPD. Initial version was manually edited by dimgel:
//      - fixed long (PostgreSQL-generated) and random (Hibernate-generated) UK/FK names;
//      - placed setPrimaryKeyNoAutoInc() on table ACTOR_PASSWORD (see tnms #5151-52).
//      Please keep these updates and don't regenerate from non-empty database; see wfe-codegen-dbaware/README.txt.
//
package ru.runa.wfe.commons.dbmigration;

import java.sql.Connection;
import java.sql.Statement;

public class DbMigration0 extends DbMigration {

    @Override
    @SuppressWarnings("ConstantConditions")
    protected void executeDDLBefore() {
        executeUpdates(
                getDDLCreateSequence("seq_admin_script"),
                getDDLCreateSequence("seq_batch_presentation"),
                getDDLCreateSequence("seq_bot"),
                getDDLCreateSequence("seq_bot_station"),
                getDDLCreateSequence("seq_bot_task"),
                getDDLCreateSequence("seq_bpm_agglog_assignments"),
                getDDLCreateSequence("seq_bpm_agglog_process"),
                getDDLCreateSequence("seq_bpm_agglog_tasks"),
                getDDLCreateSequence("seq_bpm_job"),
                getDDLCreateSequence("seq_bpm_log"),
                getDDLCreateSequence("seq_bpm_process"),
                getDDLCreateSequence("seq_bpm_process_definition"),
                getDDLCreateSequence("seq_bpm_setting"),
                getDDLCreateSequence("seq_bpm_subprocess"),
                getDDLCreateSequence("seq_bpm_swimlane"),
                getDDLCreateSequence("seq_bpm_task"),
                getDDLCreateSequence("seq_bpm_token"),
                getDDLCreateSequence("seq_bpm_variable"),
                getDDLCreateSequence("seq_executor"),
                getDDLCreateSequence("seq_executor_group_member"),
                getDDLCreateSequence("seq_executor_relation"),
                getDDLCreateSequence("seq_localization"),
                getDDLCreateSequence("seq_permission_mapping"),
                getDDLCreateSequence("seq_priveleged_mapping"),
                getDDLCreateSequence("seq_profile"),
                getDDLCreateSequence("seq_relation_group"),
                getDDLCreateSequence("seq_report"),
                getDDLCreateSequence("seq_report_parameter"),
                getDDLCreateSequence("seq_substitution"),
                getDDLCreateSequence("seq_substitution_criteria"),
                getDDLCreateSequence("seq_system_log"),
                getDDLCreateSequence("seq_wfe_constants"),

                getDDLCreateTable("actor_password", list(
                        new BigintColumnDef("actor_id").notNull().primaryKeyNoAutoInc(),
                        new BlobColumnDef("password").notNull()
                )),
                getDDLCreateTable("admin_script", list(
                        new BigintColumnDef("id").primaryKey(),
                        new VarcharColumnDef("name", 1024),
                        new BlobColumnDef("content")
                )),
                getDDLCreateTable("batch_presentation", list(
                        new BigintColumnDef("id").primaryKey(),
                        new VarcharColumnDef("category", 1024).notNull(),
                        new BlobColumnDef("fields"),
                        new IntColumnDef("range_size"),
                        new TimestampColumnDef("create_date").notNull(),
                        new BooleanColumnDef("shared").notNull(),
                        new BigintColumnDef("version"),
                        new BooleanColumnDef("is_active"),
                        new VarcharColumnDef("name", 1024).notNull(),
                        new VarcharColumnDef("class_type", 1024),
                        new BigintColumnDef("profile_id")
                )),
                getDDLCreateTable("bot", list(
                        new BigintColumnDef("id").primaryKey(),
                        new BooleanColumnDef("is_transactional"),
                        new VarcharColumnDef("password", 1024),
                        new TimestampColumnDef("create_date").notNull(),
                        new BooleanColumnDef("is_sequential"),
                        new BigintColumnDef("transactional_timeout"),
                        new TimestampColumnDef("bound_due_date"),
                        new BigintColumnDef("bound_process_id"),
                        new VarcharColumnDef("bound_subprocess_id", 255),
                        new VarcharColumnDef("username", 1024),
                        new BigintColumnDef("version"),
                        new BigintColumnDef("bot_station_id").notNull()
                )),
                getDDLCreateTable("bot_station", list(
                        new BigintColumnDef("id").primaryKey(),
                        new TimestampColumnDef("create_date").notNull(),
                        new BigintColumnDef("version"),
                        new VarcharColumnDef("address", 1024),
                        new VarcharColumnDef("name", 1024).notNull()
                )),
                getDDLCreateTable("bot_task", list(
                        new BigintColumnDef("id").primaryKey(),
                        new TimestampColumnDef("create_date").notNull(),
                        new BlobColumnDef("embedded_file"),
                        new VarcharColumnDef("embedded_file_name", 1024),
                        new BooleanColumnDef("is_sequential"),
                        new VarcharColumnDef("task_handler", 1024),
                        new BigintColumnDef("version"),
                        new BlobColumnDef("configuration"),
                        new VarcharColumnDef("name", 1024),
                        new BigintColumnDef("bot_id").notNull()
                )),
                getDDLCreateTable("bpm_agglog_assignments", list(
                        new CharColumnDef("discriminator", 1).notNull(),
                        new BigintColumnDef("id").primaryKey(),
                        new VarcharColumnDef("new_executor_name", 1024),
                        new VarcharColumnDef("old_executor_name", 1024),
                        new TimestampColumnDef("assignment_date").notNull(),
                        new BigintColumnDef("assignment_object_id"),
                        new IntColumnDef("idx")
                )),
                getDDLCreateTable("bpm_agglog_process", list(
                        new BigintColumnDef("id").primaryKey(),
                        new BigintColumnDef("process_id").notNull(),
                        new BigintColumnDef("parent_process_id"),
                        new VarcharColumnDef("cancel_actor_name", 1024),
                        new IntColumnDef("end_reason").notNull(),
                        new VarcharColumnDef("start_actor_name", 1024),
                        new TimestampColumnDef("create_date").notNull(),
                        new TimestampColumnDef("end_date")
                )),
                getDDLCreateTable("bpm_agglog_tasks", list(
                        new BigintColumnDef("id").primaryKey(),
                        new VarcharColumnDef("initial_actor_name", 1024),
                        new VarcharColumnDef("complete_actor_name", 1024),
                        new IntColumnDef("end_reason").notNull(),
                        new VarcharColumnDef("swimlane_name", 1024),
                        new BigintColumnDef("token_id").notNull(),
                        new VarcharColumnDef("task_name", 1024).notNull(),
                        new BigintColumnDef("task_id").notNull(),
                        new TimestampColumnDef("create_date").notNull(),
                        new TimestampColumnDef("end_date"),
                        new TimestampColumnDef("deadline_date"),
                        new VarcharColumnDef("node_id", 1024).notNull(),
                        new IntColumnDef("task_index"),
                        new BigintColumnDef("process_id").notNull()
                )),
                getDDLCreateTable("bpm_job", list(
                        new CharColumnDef("discriminator", 1).notNull(),
                        new BigintColumnDef("id").primaryKey(),
                        new TimestampColumnDef("due_date"),
                        new TimestampColumnDef("create_date").notNull(),
                        new VarcharColumnDef("due_date_expression", 255),
                        new BigintColumnDef("version"),
                        new VarcharColumnDef("name", 1024),
                        new VarcharColumnDef("repeat_duration", 1024),
                        new VarcharColumnDef("transition_name", 1024),
                        new BigintColumnDef("token_id"),
                        new BigintColumnDef("process_id").notNull()
                )),
                getDDLCreateTable("bpm_log", list(
                        new CharColumnDef("discriminator", 1).notNull(),
                        new BigintColumnDef("id").primaryKey(),
                        new VarcharColumnDef("severity", 1024).notNull(),
                        new BigintColumnDef("token_id"),
                        new TimestampColumnDef("create_date").notNull(),
                        new VarcharColumnDef("node_id", 1024),
                        new BigintColumnDef("process_id").notNull(),
                        new BlobColumnDef("bytes"),
                        new VarcharColumnDef("content", 4000)
                )),
                getDDLCreateTable("bpm_process", list(
                        new BigintColumnDef("id").primaryKey(),
                        new VarcharColumnDef("execution_status", 255).notNull(),
                        new BigintColumnDef("parent_id"),
                        new TimestampColumnDef("end_date"),
                        new TimestampColumnDef("start_date"),
                        new VarcharColumnDef("tree_path", 1024),
                        new BigintColumnDef("version"),
                        new BigintColumnDef("definition_id").notNull(),
                        new BigintColumnDef("root_token_id").notNull()
                )),
                getDDLCreateTable("bpm_process_definition", list(
                        new BigintColumnDef("id").primaryKey(),
                        new TimestampColumnDef("subprocess_binding_date"),
                        new TimestampColumnDef("update_date"),
                        new VarcharColumnDef("category", 1024).notNull(),
                        new TimestampColumnDef("create_date").notNull(),
                        new BigintColumnDef("version").notNull(),
                        new VarcharColumnDef("description", 1024),
                        new VarcharColumnDef("name", 1024).notNull(),
                        new VarcharColumnDef("language", 1024).notNull(),
                        new BlobColumnDef("bytes"),
                        new BigintColumnDef("update_user_id"),
                        new BigintColumnDef("create_user_id")
                )),
                getDDLCreateTable("bpm_setting", list(
                        new BigintColumnDef("id").primaryKey(),
                        new VarcharColumnDef("name", 1024).notNull(),
                        new VarcharColumnDef("value", 1024),
                        new VarcharColumnDef("file_name", 1024).notNull()
                )),
                getDDLCreateTable("bpm_subprocess", list(
                        new BigintColumnDef("id").primaryKey(),
                        new TimestampColumnDef("create_date").notNull(),
                        new VarcharColumnDef("parent_node_id", 1024),
                        new IntColumnDef("subprocess_index"),
                        new BigintColumnDef("parent_token_id"),
                        new BigintColumnDef("parent_process_id").notNull(),
                        new BigintColumnDef("process_id").notNull()
                )),
                getDDLCreateTable("bpm_swimlane", list(
                        new BigintColumnDef("id").primaryKey(),
                        new TimestampColumnDef("create_date").notNull(),
                        new BigintColumnDef("version"),
                        new VarcharColumnDef("name", 1024),
                        new BigintColumnDef("process_id"),
                        new BigintColumnDef("executor_id")
                )),
                getDDLCreateTable("bpm_task", list(
                        new BigintColumnDef("id").primaryKey(),
                        new TimestampColumnDef("create_date").notNull(),
                        new TimestampColumnDef("deadline_date"),
                        new TimestampColumnDef("assign_date"),
                        new VarcharColumnDef("node_id", 1024),
                        new VarcharColumnDef("deadline_date_expression", 255),
                        new IntColumnDef("task_index"),
                        new BigintColumnDef("version"),
                        new VarcharColumnDef("description", 1024),
                        new VarcharColumnDef("name", 1024),
                        new BigintColumnDef("process_id"),
                        new BigintColumnDef("token_id"),
                        new BigintColumnDef("executor_id"),
                        new BigintColumnDef("swimlane_id")
                )),
                getDDLCreateTable("bpm_task_opened", list(
                        new BigintColumnDef("task_id").notNull(),
                        new BigintColumnDef("executor_id")
                )),
                getDDLCreateTable("bpm_token", list(
                        new BigintColumnDef("id").primaryKey(),
                        new VarcharColumnDef("error_message", 1024),
                        new VarcharColumnDef("transition_id", 1024),
                        new VarcharColumnDef("execution_status", 255).notNull(),
                        new VarcharColumnDef("message_selector", 1024),
                        new TimestampColumnDef("error_date"),
                        new TimestampColumnDef("end_date"),
                        new TimestampColumnDef("start_date"),
                        new VarcharColumnDef("node_id", 1024),
                        new BooleanColumnDef("reactivate_parent"),
                        new VarcharColumnDef("node_type", 1024),
                        new BigintColumnDef("version"),
                        new VarcharColumnDef("name", 1024),
                        new BigintColumnDef("process_id"),
                        new BigintColumnDef("parent_id")
                )),
                getDDLCreateTable("bpm_variable", list(
                        new CharColumnDef("discriminator", 1).notNull(),
                        new BigintColumnDef("id").primaryKey(),
                        new TimestampColumnDef("create_date").notNull(),
                        new VarcharColumnDef("stringvalue", 1024),
                        new CharColumnDef("converter", 1),
                        new BigintColumnDef("version"),
                        new VarcharColumnDef("name", 1024),
                        new TimestampColumnDef("datevalue"),
                        new BlobColumnDef("bytes"),
                        new BigintColumnDef("longvalue"),
                        new DoubleColumnDef("doublevalue"),
                        new BigintColumnDef("process_id").notNull()
                )),
                getDDLCreateTable("executor", list(
                        new VarcharColumnDef("discriminator", 1).notNull(),
                        new BigintColumnDef("id").primaryKey(),
                        new TimestampColumnDef("create_date").notNull(),
                        new VarcharColumnDef("full_name", 1024),
                        new BigintColumnDef("version"),
                        new VarcharColumnDef("description", 1024),
                        new VarcharColumnDef("name", 1024).notNull(),
                        new VarcharColumnDef("e_mail", 255),
                        new BigintColumnDef("process_id"),
                        new VarcharColumnDef("phone", 1024),
                        new VarcharColumnDef("department", 1024),
                        new VarcharColumnDef("title", 1024),
                        new BigintColumnDef("code"),
                        new BooleanColumnDef("is_active"),
                        new VarcharColumnDef("node_id", 1024),
                        new IntColumnDef("escalation_level"),
                        new BigintColumnDef("escalation_executor_id")
                )),
                getDDLCreateTable("executor_group_member", list(
                        new BigintColumnDef("id").primaryKey(),
                        new TimestampColumnDef("create_date").notNull(),
                        new BigintColumnDef("version"),
                        new BigintColumnDef("group_id").notNull(),
                        new BigintColumnDef("executor_id").notNull()
                )),
                getDDLCreateTable("executor_relation", list(
                        new BigintColumnDef("id").primaryKey(),
                        new TimestampColumnDef("create_date").notNull(),
                        new VarcharColumnDef("description", 1024),
                        new VarcharColumnDef("name", 1024)
                )),
                getDDLCreateTable("executor_relation_pair", list(
                        new BigintColumnDef("id").primaryKey(),
                        new TimestampColumnDef("create_date").notNull(),
                        new BigintColumnDef("executor_to").notNull(),
                        new BigintColumnDef("executor_from").notNull(),
                        new BigintColumnDef("relation_id").notNull()
                )),
                getDDLCreateTable("localization", list(
                        new BigintColumnDef("id").primaryKey(),
                        new TimestampColumnDef("create_date").notNull(),
                        new VarcharColumnDef("name", 1024),
                        new VarcharColumnDef("value", 1024)
                )),
                getDDLCreateTable("permission_mapping", list(
                        new BigintColumnDef("id").primaryKey(),
                        new BigintColumnDef("object_id").notNull(),
                        new VarcharColumnDef("object_type", 255).notNull(),
                        new VarcharColumnDef("permission", 255).notNull(),
                        new BigintColumnDef("executor_id").notNull()
                )),
                getDDLCreateTable("priveleged_mapping", list(
                        new BigintColumnDef("id").primaryKey(),
                        new VarcharColumnDef("type", 1024).notNull(),
                        new BigintColumnDef("executor_id").notNull()
                )),
                getDDLCreateTable("profile", list(
                        new BigintColumnDef("id").primaryKey(),
                        new TimestampColumnDef("create_date").notNull(),
                        new BigintColumnDef("version"),
                        new BigintColumnDef("actor_id").notNull()
                )),
                getDDLCreateTable("report", list(
                        new BigintColumnDef("id").primaryKey(),
                        new VarcharColumnDef("category", 1024),
                        new BlobColumnDef("compiled_report").notNull(),
                        new VarcharColumnDef("config_type", 1024).notNull(),
                        new BigintColumnDef("version").notNull(),
                        new VarcharColumnDef("description", 2048),
                        new VarcharColumnDef("name", 1024).notNull()
                )),
                getDDLCreateTable("report_parameter", list(
                        new BigintColumnDef("id").primaryKey(),
                        new VarcharColumnDef("inner_name", 1024).notNull(),
                        new BooleanColumnDef("required").notNull(),
                        new VarcharColumnDef("name", 1024).notNull(),
                        new VarcharColumnDef("type", 1024).notNull(),
                        new BigintColumnDef("report_id").notNull()
                )),
                getDDLCreateTable("substitution", list(
                        new VarcharColumnDef("discriminator", 1).notNull(),
                        new BigintColumnDef("id").primaryKey(),
                        new TimestampColumnDef("create_date").notNull(),
                        new BigintColumnDef("actor_id").notNull(),
                        new VarcharColumnDef("org_function", 1024).notNull(),
                        new BooleanColumnDef("is_external").notNull(),
                        new IntColumnDef("position_index").notNull(),
                        new BigintColumnDef("version"),
                        new BooleanColumnDef("enabled_flag").notNull(),
                        new BigintColumnDef("criteria_id")
                )),
                getDDLCreateTable("substitution_criteria", list(
                        new VarcharColumnDef("discriminator", 31).notNull(),
                        new BigintColumnDef("id").primaryKey(),
                        new TimestampColumnDef("create_date").notNull(),
                        new VarcharColumnDef("conf", 1024),
                        new VarcharColumnDef("name", 1024).notNull()
                )),
                getDDLCreateTable("system_log", list(
                        new VarcharColumnDef("discriminator", 31).notNull(),
                        new BigintColumnDef("id").primaryKey(),
                        new TimestampColumnDef("create_date").notNull(),
                        new BigintColumnDef("actor_id").notNull(),
                        new BigintColumnDef("process_definition_version"),
                        new VarcharColumnDef("process_definition_name", 1024),
                        new BigintColumnDef("process_id")
                )),
                getDDLCreateTable("wfe_constants", list(
                        new BigintColumnDef("id").primaryKey(),
                        new VarcharColumnDef("name", 1024),
                        new VarcharColumnDef("value", 1024)
                )),

                getDDLCreateIndex("batch_presentation", "ix_batch_presentation_profile", "profile_id"),
                getDDLCreateIndex("bot", "ix_bot_station", "bot_station_id"),
                getDDLCreateIndex("bot_task", "ix_bot_task_bot", "bot_id"),
                getDDLCreateIndex("bpm_agglog_assignments", "ix_agglog_assign_date", "assignment_date"),
                getDDLCreateIndex("bpm_agglog_assignments", "ix_agglog_assign_executor", "new_executor_name"),
                getDDLCreateIndex("bpm_agglog_process", "ix_agglog_process_create_date", "create_date"),
                getDDLCreateIndex("bpm_agglog_process", "ix_agglog_process_end_date", "end_date"),
                getDDLCreateIndex("bpm_agglog_process", "ix_agglog_process_instance", "process_id"),
                getDDLCreateIndex("bpm_agglog_tasks", "ix_agglog_tasks_create_date", "create_date"),
                getDDLCreateIndex("bpm_agglog_tasks", "ix_agglog_tasks_end_date", "end_date"),
                getDDLCreateIndex("bpm_agglog_tasks", "ix_agglog_tasks_process", "process_id"),
                getDDLCreateIndex("bpm_job", "ix_job_process", "process_id"),
                getDDLCreateIndex("bpm_log", "ix_log_process", "process_id"),
                getDDLCreateIndex("bpm_process", "ix_process_definition", "definition_id"),
                getDDLCreateIndex("bpm_process", "ix_process_root_token", "root_token_id"),
                getDDLCreateIndex("bpm_subprocess", "ix_subprocess_parent_process", "parent_process_id"),
                getDDLCreateIndex("bpm_subprocess", "ix_subprocess_process", "process_id"),
                getDDLCreateIndex("bpm_swimlane", "ix_swimlane_process", "process_id"),
                getDDLCreateIndex("bpm_task", "ix_task_executor", "executor_id"),
                getDDLCreateIndex("bpm_task", "ix_task_process", "process_id"),
                getDDLCreateIndex("bpm_token", "ix_message_selector", "message_selector"),
                getDDLCreateIndex("bpm_token", "ix_token_parent", "parent_id"),
                getDDLCreateIndex("bpm_token", "ix_token_process", "process_id"),
                getDDLCreateIndex("bpm_variable", "ix_variable_name", "name"),
                getDDLCreateIndex("bpm_variable", "ix_variable_process", "process_id"),
                getDDLCreateIndex("executor", "ix_executor_code", "code"),
                getDDLCreateIndex("executor_group_member", "ix_member_executor", "executor_id"),
                getDDLCreateIndex("executor_group_member", "ix_member_group", "group_id"),
                getDDLCreateIndex("executor_relation_pair", "ix_erp_executor_from", "executor_from"),
                getDDLCreateIndex("executor_relation_pair", "ix_erp_executor_to", "executor_to"),
                getDDLCreateIndex("executor_relation_pair", "ix_erp_relation", "relation_id"),
                getDDLCreateIndex("permission_mapping", "ix_permission_mapping_data", "executor_id", "object_type", "permission", "object_id"),
                getDDLCreateIndex("priveleged_mapping", "ix_privelege_type", "type"),
                getDDLCreateIndex("substitution", "ix_substitution_actor", "actor_id"),
                getDDLCreateIndex("substitution", "ix_substitution_criteria", "criteria_id"),

                getDDLCreateUniqueKey("bot_station", "uk_bot_station_name", "name"),
                getDDLCreateUniqueKey("bpm_variable", "uk_variable_2", "process_id", "name"),
                getDDLCreateUniqueKey("executor", "uk_executor_name", "name"),
                getDDLCreateUniqueKey("executor_group_member", "uk_executor_group_member_2", "executor_id", "group_id"),
                getDDLCreateUniqueKey("executor_relation", "uk_executor_relation_name", "name"),
                getDDLCreateUniqueKey("localization", "uk_localization_name", "name"),
                getDDLCreateUniqueKey("permission_mapping", "uk_permission_mapping_4", "object_id", "object_type", "permission", "executor_id"),
                getDDLCreateUniqueKey("profile", "uk_profile_actor_id", "actor_id"),
                getDDLCreateUniqueKey("report", "uk_report_name", "name"),
                getDDLCreateUniqueKey("substitution", "uk_substitution_2", "position_index", "actor_id"),
                getDDLCreateUniqueKey("wfe_constants", "uk_wfe_constants_name", "name"),

                getDDLCreateForeignKey("batch_presentation", "fk_batch_presentation_profile", "profile_id", "profile", "id"),
                getDDLCreateForeignKey("bot", "fk_bot_station", "bot_station_id", "bot_station", "id"),
                getDDLCreateForeignKey("bot_task", "fk_bot_task_bot", "bot_id", "bot", "id"),
                getDDLCreateForeignKey("bpm_agglog_assignments", "fk_agglog_assignments_1", "assignment_object_id", "bpm_agglog_tasks", "id"),
                getDDLCreateForeignKey("bpm_job", "fk_job_process", "process_id", "bpm_process", "id"),
                getDDLCreateForeignKey("bpm_job", "fk_job_token", "token_id", "bpm_token", "id"),
                getDDLCreateForeignKey("bpm_process", "fk_process_definition", "definition_id", "bpm_process_definition", "id"),
                getDDLCreateForeignKey("bpm_process", "fk_process_root_token", "root_token_id", "bpm_token", "id"),
                getDDLCreateForeignKey("bpm_process_definition", "fk_definition_create_user", "create_user_id", "executor", "id"),
                getDDLCreateForeignKey("bpm_process_definition", "fk_definition_update_user", "update_user_id", "executor", "id"),
                getDDLCreateForeignKey("bpm_subprocess", "fk_subprocess_parent_process", "parent_process_id", "bpm_process", "id"),
                getDDLCreateForeignKey("bpm_subprocess", "fk_subprocess_process", "process_id", "bpm_process", "id"),
                getDDLCreateForeignKey("bpm_subprocess", "fk_subprocess_token", "parent_token_id", "bpm_token", "id"),
                getDDLCreateForeignKey("bpm_swimlane", "fk_swimlane_executor", "executor_id", "executor", "id"),
                getDDLCreateForeignKey("bpm_swimlane", "fk_swimlane_process", "process_id", "bpm_process", "id"),
                getDDLCreateForeignKey("bpm_task", "fk_task_executor", "executor_id", "executor", "id"),
                getDDLCreateForeignKey("bpm_task", "fk_task_process", "process_id", "bpm_process", "id"),
                getDDLCreateForeignKey("bpm_task", "fk_task_swimlane", "swimlane_id", "bpm_swimlane", "id"),
                getDDLCreateForeignKey("bpm_task", "fk_task_token", "token_id", "bpm_token", "id"),
                getDDLCreateForeignKey("bpm_task_opened", "fk_task_opened_task", "task_id", "bpm_task", "id"),
                getDDLCreateForeignKey("bpm_token", "fk_token_parent", "parent_id", "bpm_token", "id"),
                getDDLCreateForeignKey("bpm_token", "fk_token_process", "process_id", "bpm_process", "id"),
                getDDLCreateForeignKey("bpm_variable", "fk_variable_process", "process_id", "bpm_process", "id"),
                getDDLCreateForeignKey("executor", "fk_group_escalation_executor", "escalation_executor_id", "executor", "id"),
                getDDLCreateForeignKey("executor_group_member", "fk_member_executor", "executor_id", "executor", "id"),
                getDDLCreateForeignKey("executor_group_member", "fk_member_group", "group_id", "executor", "id"),
                getDDLCreateForeignKey("executor_relation_pair", "fk_erp_executor_from", "executor_from", "executor", "id"),
                getDDLCreateForeignKey("executor_relation_pair", "fk_erp_executor_to", "executor_to", "executor", "id"),
                getDDLCreateForeignKey("executor_relation_pair", "fk_erp_relation", "relation_id", "executor_relation", "id"),
                getDDLCreateForeignKey("permission_mapping", "fk_permission_executor", "executor_id", "executor", "id"),
                getDDLCreateForeignKey("priveleged_mapping", "fk_pm_executor", "executor_id", "executor", "id"),
                getDDLCreateForeignKey("profile", "fk_profile_actor", "actor_id", "executor", "id"),
                getDDLCreateForeignKey("report_parameter", "fk_report_parameter_report", "report_id", "report", "id"),
                getDDLCreateForeignKey("substitution", "fk_substitution_criteria", "criteria_id", "substitution_criteria", "id")
        );
    }

    @Override
    public void executeDML(Connection conn) throws Exception {
        try (Statement stmt = conn.createStatement()) {
            stmt.executeUpdate("insert into " + schemaPrefix + "wfe_constants (" + insertPkColumn() + "name, value) values (" +
                    insertPkNextVal("wfe_constants") + "'ru.runa.database_version', 59)");
        }
    }
}
